using System.Collections.Generic;

/// <summary>
/// BẢNG DỊCH VIỆT → ANH. Khoá là CHÍNH CÂU TIẾNG VIỆT trong game.
/// ══════════════════════════════════════════════════════════════════════════════
///
/// ĐỢT 1 (Sếp duyệt 04/09): chỉ dịch UI người chơi gặp nhiều nhất — HUD, Cài đặt, Hồ sơ,
/// Shop, Kho, Lên cấp, Nhiệm vụ, Bếp, Tàu, Tutorial.
/// ĐỢT SAU: tên món ăn, tên nguyên liệu, 315 tên đơn hàng (OrderNameBank), mô tả nhiệm vụ.
///
/// LUẬT THÊM CÂU MỚI:
///   • Khoá phải khớp TỪNG KÝ TỰ với câu trong code/scene, kể cả dấu và khoảng trắng.
///   • Chưa có câu nào đó ⇒ game tự hiện tiếng Việt, KHÔNG lỗi. Cứ bổ sung dần.
///   • Không xoá khoá cũ khi chưa chắc không còn ai dùng.
///
/// [Localization]
/// </summary>
public static class LocStringTable
{
    public static readonly Dictionary<string, string> EN = new Dictionary<string, string>
    {
        // ── HUD & điều hướng chính ──────────────────────────────────────────
        { "Cửa hàng",        "Shop" },
        { "CỬA HÀNG",        "SHOP" },
        { "Kho",             "Storage" },
        { "KHO",             "STORAGE" },
        { "Bảng tin chợ",    "Market Board" },
        { "BẢNG TIN CHỢ",    "MARKET BOARD" },
        { "Nấu ăn",          "Cooking" },
        { "NẤU ĂN",          "COOKING" },
        { "Về nông trại",    "Back to Farm" },
        { "VỀ NÔNG TRẠI",    "BACK TO FARM" },
        { "Sửa",             "Edit" },
        { "SỬA",             "EDIT" },

        // ── Cài đặt ─────────────────────────────────────────────────────────
        { "CÀI ĐẶT",         "SETTINGS" },
        { "Cài đặt",         "Settings" },
        { "Âm thanh game",   "Music" },
        { "Âm thanh VFX",    "Sound Effects" },
        { "Ngôn ngữ",        "Language" },
        { "Tiếng Việt",      "Tiếng Việt" },   // tên ngôn ngữ giữ nguyên bản ngữ — chuẩn quốc tế
        { "English",         "English" },
        { "BẬT",             "ON" },
        { "TẮT",             "OFF" },
        { "ĐÓNG",            "CLOSE" },
        { "Đóng",            "Close" },
        { "CHƠI LẠI TỪ ĐẦU", "RESET PROGRESS" },
        { "Chơi lại từ đầu", "Reset Progress" },
        { "Xoá dữ liệu",     "Reset Data" },
        { "Bạn có chắc muốn xoá toàn bộ dữ liệu và chơi lại từ đầu không?", "Are you sure you want to reset all data and restart from Level 1?" },

        // ── Hồ sơ người chơi ────────────────────────────────────────────────
        { "HỒ SƠ",           "PROFILE" },
        { "Hồ sơ",           "Profile" },
        { "Tên nông trại",   "Farm Name" },
        { "Cấp độ",          "Level" },
        { "Cấp",             "Lv" },
        { "Chọn avatar",     "Choose Avatar" },
        { "LƯU HỒ SƠ",       "SAVE PROFILE" },
        { "Sức chứa kho",    "Storage Capacity" },
        { "Điểm nấu ăn",     "Recipes Cooked" },
        { "Tiền vàng",       "Gold" },
        { "Nhiệm vụ",        "Quests" },
        { "đã xong",         "done" },
        { "ô",               "slots" },
        { "món",             "dishes" },

        // ── Lên cấp ─────────────────────────────────────────────────────────
        { "LÊN CẤP!",        "LEVEL UP!" },
        { "Lên cấp!",        "Level Up!" },
        { "Bắt đầu nào",     "Let's Go" },
        { "BẮT ĐẦU NÀO",     "LET'S GO" },
        { "MỚI",             "NEW" },
        { "Phần thưởng",     "Rewards" },
        { "Đã mở khoá",      "Unlocked" },

        // ── Bảng đơn hàng ───────────────────────────────────────────────────
        { "BẢNG ĐƠN HÀNG",   "ORDER BOARD" },
        { "GIAO HÀNG",       "DELIVER" },
        { "Giao hàng",       "Deliver" },

        // ── Bếp ─────────────────────────────────────────────────────────────
        { "ĐƠN CỦA KHÁCH",   "CUSTOMER ORDERS" },
        { "BẢNG CÔNG THỨC",  "RECIPE BOOK" },
        { "Tất cả",          "All" },
        { "Dễ",              "Easy" },
        { "Vừa",             "Medium" },
        { "Khó",             "Hard" },
        { "Nguyên liệu",     "Ingredients" },
        { "Gia vị",          "Seasonings" },
        { "Bàn sơ chế",      "Prep Table" },
        { "Trình bày",       "Plating" },
        { "Bỏ hết",          "Clear All" },
        { "VÀO KHO",         "TO STORAGE" },
        { "Lò chưa nhóm",    "Oven not lit" },
        { "CHỌN NGUYÊN LIỆU","PICK INGREDIENTS" },
        { "chạm khay bên dưới", "tap the tray below" },
        { "MÓN HÔM NAY (+vàng)", "TODAY'S SPECIALS (+gold)" },

        // ── Tàu chở hàng ────────────────────────────────────────────────────
        { "TÀU CHỞ HÀNG",    "CARGO TRAIN" },
        { "NẠP HÀNG",        "LOAD CARGO" },
        { "GA HÀNG",         "STATION" },
        { "THÊM HÀNG",       "ADD GOODS" },
        { "NẠP TẤT CẢ",      "LOAD ALL" },
        { "Trong kho:",      "In storage:" },
        { "Chạm vào toa để nạp hàng — nạp đủ các toa yêu cầu, tàu sẽ khởi hành!",
          "Tap a wagon to load it — fill every wagon and the train departs!" },

        // ── Chung ───────────────────────────────────────────────────────────
        { "Xác nhận",        "Confirm" },
        { "Huỷ",             "Cancel" },
        { "Hủy",             "Cancel" },
        { "Mua",             "Buy" },
        { "Bán",             "Sell" },
        { "Tiếp tục",        "Continue" },
        { "Bỏ qua",          "Skip" },
        { "Không đủ vàng!",  "Not enough gold!" },
        { "Kho đã đầy!",     "Storage is full!" },

        // -- HUD - Cap - Tien te - Kho - Nhiem vu - Thanh tuu - Diem danh --
        { "CẤP", "LEVEL" },
        { "CẤP MỚI!", "NEW LEVEL!" },
        { "Cấp 1 – 30", "Level 1 – 30" },
        { "Cấp 18", "Level 18" },
        { "Cấp 7 · 175 Slot", "Level 7 · 175 Slots" },
        { "(Đạt cấp tối đa)", "(Max level reached)" },
        { "Cấp độ 7", "Level 7" },
        { "Cần đạt cấp", "Requires level" },
        { "Chưa đủ cấp", "Level too low" },
        { "Mở ở cấp", "Unlocks at Lv" },
        { "Mở ở cấp 5", "Unlocks at Lv 5" },
        { "Mở ở cấp 6", "Unlocks at Lv 6" },
        { "Khoá", "Locked" },
        { "chưa mở", "locked" },
        { "Trống", "Empty" },
        { "CỦA BẠN", "YOURS" },
        { "Bạn", "You" },
        { "VÀNG", "GOLD" },
        { "Vàng", "Gold" },
        { "Vàng — cộng thẳng vào ví của bạn", "Gold — added straight to your wallet" },
        { "KIM CƯƠNG", "GEMS" },
        { "Kim cương", "Gems" },
        { "Kim cương — tiền tệ cao cấp", "Gems — premium currency" },
        { "Không đủ vàng", "Not enough gold" },
        { "Không đủ tiền!", "Not enough coins!" },
        { "Không đủ kim cương", "Not enough gems" },
        { "Không đủ vàng để làm mới", "Not enough gold to refresh" },
        { "Không đủ kim cương để tăng tốc tàu.", "Not enough gems to speed up the train." },
        { "MIỄN PHÍ", "FREE" },
        { "Nhận", "Claim" },
        { "Đã nhận", "Claimed" },
        { "Đã thu", "Collected" },
        { "Đã cho", "Fed" },
        { "Đã mua!", "Purchased!" },
        { "Đã mua hạt giống!", "Seeds purchased!" },
        { "Đã rõ", "Got it!" },
        { "Thêm", "Add" },
        { "TăngSL", "Qty +" },
        { "Đi làm", "Go to work" },
        { "Đang làm", "In progress" },
        { "Đi lấy thêm vật phẩm", "Get more items" },
        { "Chọn vật phẩm", "Choose Item" },
        { "Chi tiết vật phẩm", "Item Details" },
        { "Tìm vật phẩm...", "Search items..." },
        { "Vật phẩm", "Items" },
        { "Vật liệu", "Materials" },
        { "Nông sản", "Crops" },
        { "Nông sản — nguyên liệu nấu ăn, bán được ở chợ", "Crops — cooking ingredients you can sell at the Market" },
        { "Món ăn", "Dishes" },
        { "Hạt giống", "Seeds" },
        { "Hạt giống — gieo xuống ô đất để trồng", "Seeds — sow them on a plot to grow" },
        { "Hạt giống dùng để gieo trồng tại các ô đất nông trại. Không dùng làm nguyên liệu nấu ăn.", "Seeds for sowing on your farm plots. They cannot be used as cooking ingredients." },
        { "Vật phẩm lưu trữ trong kho nông trại. Dùng cho chế biến và hoàn thành đơn hàng.", "Items kept in your farm storage. Used for cooking and completing orders." },
        { "Món ăn đã được chế biến thơm ngon. Dùng để phục vụ thực khách tại nhà hàng.", "A freshly cooked dish, ready to serve hungry diners at the restaurant." },
        { "Nông phẩm chăn nuôi chất lượng cao. Cần thiết cho các món ăn dinh dưỡng tại bếp.", "Top-quality animal produce. Essential for the most nourishing dishes in the kitchen." },
        { "Hoa trang trí và cảnh quan nông trại. Không chuyển vào bếp nấu ăn.", "Flowers for farm decor and landscaping. They cannot be sent to the kitchen." },
        { "Công trình / Trang trí nông trại. Không chuyển vào bếp.", "Farm buildings and decor. They cannot be sent to the kitchen." },
        { "Vật phẩm quà tặng", "Gift Item" },
        { "Vật phẩm quà tặng — cộng thẳng vào kho", "Gift item — added straight to your storage" },
        { "Công trình", "Building" },
        { "Trang trí", "Decor" },
        { "Chăn nuôi", "Livestock" },
        { "Chế biến", "Cook" },
        { "KHO VẬT PHẨM", "ITEM STORAGE" },
        { "KHO ĐẦY!", "STORAGE FULL!" },
        { "Kho chưa sẵn sàng", "Storage not ready" },
        { "Kho vừa thay đổi, thử lại nhé.", "Storage just changed, please try again." },
        { "Chưa mở được kho, thử lại sau.", "Can't open Storage, try again later." },
        { "Kho đầy — bán bớt hoặc nâng cấp kho", "Storage full — sell some or upgrade it" },
        { "Kho đầy — bán bớt hoặc nâng cấp kho rồi thu thưởng tàu.", "Storage full — sell some or upgrade, then claim the train reward." },
        { "Túi nông sản đã đầy — bán bớt hoặc nâng cấp kho rồi thu lại!", "Your crop bag is full — sell some or upgrade storage, then collect!" },
        { "Số lượng chuyển:", "Amount to move:" },
        { "Số lượng trong kho: 0", "In storage: 0" },
        { "CHUYỂN VÀO KHO", "MOVE TO STORAGE" },
        { "Chuyển vào kho", "Move to Storage" },
        { "CHUYỂN BẾP", "SEND TO KITCHEN" },
        { "Chuyển sang bếp", "Send to Kitchen" },
        { "KHÔNG PHẢI ĐỒ NẤU", "NOT COOKABLE" },
        { "Nhấp vào vật phẩm ở danh sách bên trái để xem thông tin chi tiết và chuyển sang bếp.", "Tap an item on the left to see its details and send it to the kitchen." },
        { "NÂNG CẤP", "UPGRADE" },
        { "Nâng cấp", "Upgrade" },
        { "NÂNG CẤP KHO", "UPGRADE STORAGE" },
        { "Nâng cấp kho lên cấp 2", "Upgrade Storage to level 2" },
        { "Yêu cầu nâng cấp", "Upgrade required" },
        { "Nâng cấp nhà kho để chứa được nhiều nông sản và nguyên liệu quý hơn! 🌾", "Upgrade your storage to hold more crops and precious ingredients! 🌾" },
        { "120 ô", "120 slots" },
        { "18 đã xong", "18 done" },
        { "35 món", "35 dishes" },
        { "Mốc thành tựu", "Milestone" },
        { "THÀNH TỰU", "ACHIEVEMENTS" },
        { "Thành tựu", "Achievements" },
        { "Đã hoàn tất mọi thành tựu!", "All achievements complete!" },
        { "Đã xong cả mốc này! Sang mốc sau để nhận thêm.", "This milestone is done! On to the next one for more." },
        { "Hoàn thành các mốc để mở rương thưởng!", "Complete milestones to open reward chests!" },
        { "Hoàn thành tất cả nhiệm vụ để nhận thưởng đặc biệt!", "Complete every quest for a special reward!" },
        { "NHIỆM VỤ", "QUESTS" },
        { "NHIỆM VỤ MỚI", "NEW QUEST" },
        { "Phần thưởng:", "Rewards:" },
        { "Phần thưởng mốc — cả trang", "Milestone rewards — full page" },
        { "Phần thưởng tuần — điểm danh đủ 7 ngày", "Weekly reward — check in all 7 days" },
        { "Vuốt ngang để xem tất cả phần thưởng", "Swipe to see all rewards" },
        { "MỞ KHÓA PHẦN THƯỞNG MỚI", "NEW REWARDS UNLOCKED" },
        { "NHẬN QUÀ", "CLAIM GIFT" },
        { "QUÀ 1", "GIFT 1" },
        { "QUÀ 2", "GIFT 2" },
        { "QUÀ 3", "GIFT 3" },
        { "QUÀ 4", "GIFT 4" },
        { "QUÀ 5", "GIFT 5" },
        { "QUÀ 6", "GIFT 6" },
        { "Quà tuần đặc biệt đang chờ bạn!", "A special weekly gift is waiting for you!" },
        { "ĐIỂM DANH", "DAILY CHECK-IN" },
        { "Điểm danh mỗi ngày để nhận quà!", "Check in every day to get gifts!" },
        { "Hằng ngày", "Daily" },
        { "Ngày 1", "Day 1" },
        { "Ngày mai", "Tomorrow" },
        { "Rương", "Chest" },
        { "có thưởng chưa nhận", "reward not claimed" },

        // -- Cua hang - Bang tin cho - Tau - May xay - Chuong - Ruong - Bep - Don hang --
        { "LÀM MỚI", "REFRESH" },
        { "LÀM MỚI NGAY", "REFRESH NOW" },
        { "Làm mới sau:", "Refresh in:" },
        { "HỜI", "BARGAIN" },
        { "đắt", "pricey" },
        { "đang có hàng", "in stock" },
        { "Đây là hàng bạn đang bán", "This is your listing" },
        { "Món này vừa có người mua", "Someone just bought this one" },
        { "CHƯA CÓ VẬT PHẨM NÀO ĐƯỢC ĐĂNG BÁN", "NO ITEMS LISTED FOR SALE YET" },
        { "Mua 1 cái / lần", "Buy 1 at a time" },
        { "Mua 1 cái cuốc mới", "Buy a new hoe" },
        { "Ô ĐẤT", "PLOT" },
        { "Nhà Dân", "Villager House" },
        { "Mở bến số 2", "Unlock Dock 2" },
        { "Mở chợ.", "Open Market." },
        { "Mở kho.", "Open Storage." },
        { "Mở túi đồ.", "Open your bag." },
        { "Mở bảng xếp hạng.", "Open the leaderboard." },
        { "GA TÀU HOẢ", "TRAIN STATION" },
        { "TÀU ĐÃ VỀ!", "TRAIN HAS ARRIVED!" },
        { "Tàu số 01 sắp cập bến!", "Train 01 is pulling in!" },
        { "Tàu đã về ga — chạm vào ga tàu để nhận hàng!", "The train is in — tap the station to collect!" },
        { "ĐẾN", "TO" },
        { "Bến tàu du lịch mang tới rất nhiều vị khách phương xa thân thiện! 🚢", "The tourist dock brings lots of friendly visitors from far away! 🚢" },
        { "MÁY XAY THỨC ĂN", "FEED MILL" },
        { "Máy đang rảnh", "Mill is idle" },
        { "Đang xay ·", "Milling ·" },
        { "đang xay ·", "milling ·" },
        { "Đã xay xong", "Milling done" },
        { "Đã mở thêm 1 slot xay!", "1 more mill slot unlocked!" },
        { "KÉO VÀO SLOT ĐỂ XAY", "DRAG INTO A SLOT TO MILL" },
        { "Thả bao vào một SLOT TRỐNG để máy xay", "Drop the sack into an EMPTY SLOT to mill it" },
        { "HẾT SLOT TRỐNG", "NO FREE SLOTS" },
        { "Hết slot trống — thu hàng đã xong rồi thả tiếp nhé!", "No free slots — collect the finished goods first!" },
        { "Hãy mở slot theo thứ tự", "Please unlock the slots in order" },
        { "vào slot", "into slot" },
        { "vào kho!", "to storage!" },
        { "đang kéo", "dragging" },
        { "chờ thu", "collect" },
        { "CHUỒNG NUÔI", "ANIMAL PEN" },
        { "CHUỒNG GÀ", "CHICKEN PEN" },
        { "CHUỒNG HEO", "PIG PEN" },
        { "CHUỒNG BÒ", "COW PEN" },
        { "CHUỒNG BÒ SỮA", "DAIRY COW PEN" },
        { "Chuồng Gà", "Chicken Pen" },
        { "Chuồng Heo", "Pig Pen" },
        { "Chuồng Bò", "Cow Pen" },
        { "Chuồng Bò Sữa", "Dairy Cow Pen" },
        { "gà", "chickens" },
        { "lợn", "pigs" },
        { "Kéo bao thức ăn vào chuồng để cho gia súc ăn.", "Drag a feed sack into the pen to feed your animals." },
        { "Kéo chiếc rổ quét qua chuồng để thu hoạch sản phẩm.", "Sweep the basket across the pen to collect the produce." },
        { "Kéo chiếc rổ thả vào chuồng để thu hoạch sản phẩm.", "Drop the basket into the pen to collect the produce." },
        { "Kéo hạt giống để trồng.", "Drag seeds to plant them." },
        { "Kéo hạt giống hoa để trồng.", "Drag flower seeds to plant them." },
        { "Chạm ô đất, rồi kéo hạt lúa vào ô.", "Tap a plot, then drag rice seeds onto it." },
        { "KÉO LIỀM GẶT", "SWIPE THE SICKLE" },
        { "LÚA CHÍN", "RICE READY" },
        { "LÚA ĐANG LỚN", "RICE GROWING" },
        { "ĐANG TRỒNG...", "GROWING..." },
        { "LÚA MÌ", "WHEAT" },
        { "HẠT GIỐNG LÚA", "RICE SEEDS" },
        { "KHO LÚA (+4)", "RICE STORE (+4)" },
        { "BÓ LÚA VÀNG", "GOLDEN RICE SHEAF" },
        { "BƯỚC 1 — TRỒNG LÚA", "STEP 1 — PLANT RICE" },
        { "BƯỚC 2 — TĂNG TỐC", "STEP 2 — SPEED UP" },
        { "BƯỚC 3 — THU HOẠCH", "STEP 3 — HARVEST" },
        { "BƯỚC 4 — NHẬN KẾT QUẢ", "STEP 4 — CLAIM REWARD" },
        { "Thu hoạch thành công! Nhận ngay lúa vào kho.", "Great harvest! The rice goes straight into your storage." },
        { "CÔNG THỨC", "RECIPES" },
        { "CHỌN MỘT CÔNG THỨC", "PICK A RECIPE" },
        { "THIẾU NGUYÊN LIỆU", "MISSING INGREDIENTS" },
        { "Thiếu nguyên liệu", "Missing ingredients" },
        { "Thiếu vật phẩm", "Missing items" },
        { "Đơn hàng", "Order" },
        { "Đơn hàng này không còn nữa.", "This order is no longer available." },
        { "Chưa giao được đơn này.", "You can't deliver this order yet." },
        { "Không bỏ được đơn này.", "This order can't be skipped." },
        { "Thu hoạch 10 lúa", "Harvest 10 rice" },
        { "Thu hoạch 3 dưa hấu", "Harvest 3 watermelons" },
        { "Thu hoạch 5 ngô", "Harvest 5 corn" },
        { "Thu hoạch 6 cà chua", "Harvest 6 tomatoes" },
        { "Thu hoạch 8 cà rốt", "Harvest 8 carrots" },
        { "Thu thập 10 lít sữa", "Collect 10 litres of milk" },
        { "Thu thập 20 trứng gà", "Collect 20 eggs" },
        { "Thu thập 4 quả trứng gà tươi", "Collect 4 fresh eggs" },
        { "Trồng cây 15 lần", "Plant 15 times" },
        { "Tưới nước 20 ô đất", "Water 20 plots" },
        { "Bán hàng 5 lần ở chợ", "Sell 5 times at the Market" },
        { "Chăn nuôi 5 con gà", "Raise 5 chickens" },
        { "Chăn nuôi 3 con heo", "Raise 3 pigs" },
        { "Chăn nuôi 2 con bò", "Raise 2 cows" },
        { "Thu hoạch lúa và ngô để làm bột bánh mì nóng hổi giòn rụm! 🍞", "Harvest rice and corn to make dough for warm, crusty bread! 🍞" },
        { "Tưới nước mỗi ngày để hoa màu nhanh lớn và bội thu nhé! 🥕", "Water every day so your crops grow fast and give a big harvest! 🥕" },
        { "Nấu ăn tại Bếp Nông Trại để phục vụ du khách trên những chuyến tàu! 🍲", "Cook in the Farm Kitchen to serve the travellers on the trains! 🍲" },
        { "Trồng trọt, nấu những món ăn thơm ngon và xây dựng nông trại trong mơ!", "Grow crops, cook tasty dishes and build the farm of your dreams!" },
        { "Xin chào! Mình sẽ hướng dẫn bạn nhé.", "Hi there! I'll show you the ropes." },
        { "Cháu đến rồi à! Bắt tay vào việc thôi!", "You're here! Let's get to work!" },
        { "Yêu cầu: đạt Lv12 (bạn đang Lv10)", "Requires Lv12 (you're Lv10)" },

        // -- Nong san - Hat giong - Hoa - Nguyen lieu - Vat lieu - Mon an --
        { "Lúa", "Rice" },
        { "Hạt lúa", "Rice Seeds" },
        { "Hạt Lúa", "Rice Seeds" },
        { "Lúa Mì", "Wheat" },
        { "Ngô", "Corn" },
        { "Bắp", "Corn" },
        { "Bắp Ngô", "Corn" },
        { "Hạt Ngô", "Corn Seeds" },
        { "Bắp Cải", "Cabbage" },
        { "Hạt Bắp Cải", "Cabbage Seeds" },
        { "Cà Chua", "Tomato" },
        { "Hạt Cà Chua", "Tomato Seeds" },
        { "Cà Rốt", "Carrot" },
        { "Hạt Cà Rốt", "Carrot Seeds" },
        { "Khoai Tây", "Potato" },
        { "Hạt Khoai Tây", "Potato Seeds" },
        { "Bí Đỏ", "Pumpkin" },
        { "Hạt Bí Đỏ", "Pumpkin Seeds" },
        { "Dưa Hấu", "Watermelon" },
        { "Hạt Dưa Hấu", "Watermelon Seeds" },
        { "Mía", "Sugarcane" },
        { "Hạt Mía", "Sugarcane Seeds" },
        { "Nấm", "Mushroom" },
        { "Hạt Nấm", "Mushroom Seeds" },
        { "Ớt", "Chili" },
        { "Hạt Ớt", "Chili Seeds" },
        { "Hướng Dương", "Sunflower" },
        { "Hạt Hướng Dương", "Sunflower Seeds" },
        { "Hạt Chanh", "Lemon Seeds" },
        { "Hạt Tiêu", "Pepper Seeds" },
        { "Hạt Tulip", "Tulip Seeds" },
        { "Hoa Hồng", "Rose" },
        { "Hạt Hoa Hồng", "Rose Seeds" },
        { "Hoa Anh Thảo", "Primrose" },
        { "Hạt Hoa Anh Thảo", "Primrose Seeds" },
        { "Hoa Cúc Trắng", "White Daisy" },
        { "Hạt Hoa Cúc Trắng", "White Daisy Seeds" },
        { "Hoa Cúc Vạn Thọ", "Marigold" },
        { "Hạt Hoa Cúc Vạn Thọ", "Marigold Seeds" },
        { "Hoa Cẩm Tú Cầu", "Hydrangea" },
        { "Hạt Hoa Cẩm Tú Cầu", "Hydrangea Seeds" },
        { "Hoa Mẫu Đơn", "Peony" },
        { "Hạt Hoa Mẫu Đơn", "Peony Seeds" },
        { "Hoa Oải Hương", "Lavender" },
        { "Hạt Hoa Oải Hương", "Lavender Seeds" },
        { "Hạt Hoa Lan", "Orchid Seeds" },
        { "Trứng", "Egg" },
        { "Sữa", "Milk" },
        { "Phô Mai", "Cheese" },
        { "Thịt Bò", "Beef" },
        { "Thịt Gà", "Chicken" },
        { "Thịt Heo", "Pork" },
        { "Bột Gạo", "Rice Flour" },
        { "Muối", "Salt" },
        { "Tiêu", "Pepper" },
        { "Nước Mắm", "Fish Sauce" },
        { "Nước Tương", "Soy Sauce" },
        { "Rau Thơm", "Herbs" },
        { "Cám Gà", "Chicken Feed" },
        { "Cám Heo", "Pig Feed" },
        { "Cám Bò", "Cow Feed" },
        { "Gỗ", "Wood" },
        { "Gạch", "Bricks" },
        { "Đá", "Stone" },
        { "Kính", "Glass" },
        { "Đinh", "Nails" },
        { "Sơn", "Paint" },
        { "Bình tưới", "Watering Can" },
        { "Bánh Bí Đỏ Hấp Mía", "Steamed Pumpkin Cake" },
        { "Bánh Khoai Tây Nấm Chiên", "Fried Potato Mushroom Cake" },
        { "Bánh Ngô Chiên Giòn", "Crispy Corn Fritters" },
        { "Bánh Ngô Nướng Mật Mía", "Sugarcane Glazed Corn Cake" },
        { "Bò Hầm Bí Đỏ Sốt Kem", "Creamy Pumpkin Beef Stew" },
        { "Bò Hầm Cà Rốt", "Beef and Carrot Stew" },
        { "Bò Xào Tiêu", "Peppered Beef" },
        { "Bắp Cải Xào Nấm", "Cabbage Mushroom Fry" },
        { "Canh Bí Đỏ Sườn Non", "Pumpkin and Pork Rib Soup" },
        { "Canh Cà Chua Cà Rốt", "Tomato Carrot Soup" },
        { "Canh Khoai Tây Thịt Heo", "Potato and Pork Soup" },
        { "Canh Nấm Cà Chua", "Mushroom Tomato Soup" },
        { "Chè Ngô Sữa Kem", "Creamy Corn Pudding" },
        { "Cơm Chiên Bắp Cải", "Cabbage Fried Rice" },
        { "Cơm Chiên Trứng", "Egg Fried Rice" },
        { "Dưa Hấu Dầm Sữa Đá", "Iced Watermelon Milk" },
        { "Dưa Hấu Trộn Muối Ớt", "Chili Salt Watermelon" },
        { "Gà Hầm Nấm Cà Rốt", "Chicken Mushroom Stew" },
        { "Gà Nướng Lu Mật Mía", "Sugarcane Roast Chicken" },
        { "Gà Xào Bắp Cải", "Chicken Cabbage Fry" },
        { "Gà Xào Ớt", "Chili Chicken" },
        { "Khoai Tây Chiên", "French Fries" },
        { "Khoai Tây Xào Cà Rốt", "Potato Carrot Stir-Fry" },
        { "Nấm Xào Thịt Bò", "Beef Mushroom Stir-Fry" },
        { "Nước Mía Chanh", "Lemon Sugarcane Juice" },
        { "Nước Mía Ép", "Sugarcane Juice" },
        { "Nước Ép Dưa Hấu Chanh", "Watermelon Lemon Juice" },
        { "Phở Bò Tái", "Rare Beef Pho" },
        { "Salad Bắp Cải Chanh", "Lemon Cabbage Salad" },
        { "Salad Bắp Cải Cà Rốt", "Cabbage Carrot Salad" },
        { "Salad Dưa Hấu Bò Áp Chảo", "Seared Beef Watermelon Salad" },
        { "Salad Nấm Và Rau", "Mushroom Garden Salad" },
        { "Súp Bí Đỏ Kem Sữa", "Creamy Pumpkin Soup" },
        { "Súp Ngô Nấm", "Corn Mushroom Soup" },
        { "Súp Ngô Trứng", "Corn Egg Drop Soup" },
        { "Sườn Heo Xào Chua Ngọt", "Sweet and Sour Pork Ribs" },
        { "Thịt Heo Luộc Cuốn Rau", "Boiled Pork and Herb Rolls" },
        { "Trứng Chiên Cà Chua", "Tomato Omelette" },
        { "Trứng Ốp La Bò Né", "Sizzling Beef and Egg" },

        // -- Loi thoai Tutorial ------------------------------------------
        { "1:Chào mừng bạn đến với nông trại! Mình sẽ đồng hành cùng bạn xây dựng một nông trại thật trù phú nhé.", "Welcome to the farm! I'll be right here with you as we build a wonderfully rich farm together." },
        { "2:Cháu đến rồi à! Trang trại hoang tàn quá, bắt tay vào việc bằng cách vào Cửa Hàng mua một mảnh đất nhé!", "You're here! The farm looks so bare. Let's start by opening the Shop and buying a plot of land!" },
        { "3:Bấm vào đây để mở Cửa Hàng. Sau đó chọn tab Đất để mua mảnh đất đầu tiên nào!", "Tap here to open the Shop. Then pick the Land tab and buy your very first plot!" },
        { "4:Chọn mua Ô Đất ở đây — lần đầu hoàn toàn miễn phí! Nhấn Mua rồi đặt xuống map nhé.", "Grab a Plot here — the first one is completely free! Tap Buy, then place it on the map." },
        { "5:Tuyệt vời! Giờ hãy gieo hạt Lúa vào ô đất vừa đặt. Cây sẽ chín chỉ sau 5 giây thôi!", "Wonderful! Now sow Rice seeds in the plot you just placed. It ripens in only 5 seconds!" },
        { "6:Lúa chín rồi! Dùng liềm chạm vào để thu hoạch. Thu xong nhận 10 Exp và lên ngay Level 2!", "The rice is ready! Tap it with the sickle to harvest. You'll earn 10 EXP and hit Level 2!" },
        { "7:Tuyệt vời! Bạn đã có lúa rồi!\nBây giờ hãy bấm vào căn nhà có bong bóng đơn hàng để giao hàng và nhận thưởng!", "Wonderful! You've got rice now!\nTap the house with the order bubble to deliver it and claim your reward!" },
        { "8:Xuất sắc! Bạn vừa nhận được vàng và kinh nghiệm!\nTiếp tục trồng trọt và giao đơn hàng để lên cấp nhé!", "Brilliant! You just earned gold and EXP!\nKeep growing crops and delivering orders to level up!" },
        { "9:Bạn đã hiểu cách chơi rồi đó!\nHãy mở rộng nông trại, mua thêm hạt giống, và giao thật nhiều đơn hàng!\nChúc bạn chơi vui! 🌾", "You've got the hang of it!\nExpand your farm, buy more seeds and deliver lots of orders!\nHave fun! 🌾" },
        { "10:Trước tiên, chúng ta hãy cùng gieo những hạt giống lúa đầu tiên xuống ruộng nào! Hãy chạm vào ô đất nhé.", "First, let's sow your very first rice seeds in the field! Go ahead and tap a plot." },
        { "11:Chạm vào ô đất để mở khay hạt giống nào!", "Tap a plot to open the seed tray!" },
        { "12:Khay hạt giống đã mở! Kéo hạt lúa vào ô đất để gieo hạt nhé!", "The seed tray is open! Drag rice seeds onto the plot to sow them." },
        { "13:Giỏi lắm! Gieo nốt cho kín cả 8 ô ruộng nhé — bàn tay sẽ chỉ ô còn trống cho bạn.", "Nicely done! Fill all 8 plots — the hand will point to the empty ones for you." },
        { "14:Chạm vào ô lúa để kiểm tra thời gian chín nào!", "Tap a rice plot to check how long it needs!" },
        { "15:Cây đang lớn rồi! Dùng kim cương để lúa chín ngay lập tức nhé.", "Your crops are growing! Use gems to ripen the rice right away." },
        { "16:Bấm nút kim cương để lúa chín vàng óng ngay nhé!", "Tap the gem button to turn the rice golden right now!" },
        { "17:Lúa đã chín vàng rực! Hãy dùng liềm để thu hoạch nông sản nào.", "The rice is golden and ready! Use the sickle to bring in the harvest." },
        { "19:Chạm vào ô lúa chín để thu hoạch nào!", "Tap a ripe rice plot to harvest it!" },
        { "20:Quẹt liềm qua ô lúa để thu hoạch những hạt lúa vàng ươm!", "Swipe the sickle across the plot to gather that golden rice!" },
        { "21:Cả ruộng chín vàng rồi! Quẹt liềm thu hoạch nốt những ô còn lại nào.", "The whole field is golden! Swipe the sickle over the plots that are left." },
        { "22:Tuyệt vời! Thu hoạch mùa màng giúp bạn tích luỹ thật nhiều EXP để lên cấp!", "Wonderful! Harvesting your crops earns you lots of EXP to level up!" },
        { "23:Bên cạnh lúa, nông trại còn có vườn hoa hướng dương rực rỡ đấy!", "Besides rice, your farm has a bright sunflower garden too!" },
        { "24:Chạm vào chậu hoa để mở khay hạt hoa nhé!", "Tap a flower pot to open the flower seed tray!" },
        { "25:Kéo hạt giống hoa hướng dương vào chậu để gieo trồng nào!", "Drag sunflower seeds into the pot to plant them!" },
        { "26:Gieo nốt hạt hướng dương vào những chậu còn trống nhé!", "Sow sunflower seeds in the pots that are still empty!" },
        { "27:Dùng kim cương để hoa hướng dương nở rộ ngay lập tức!", "Use gems to make the sunflowers bloom right away!" },
        { "28:Hoa đã nở rực rỡ! Hãy thu hoạch bông hoa đầu tiên nào!", "They're in full bloom! Let's pick your very first flower!" },
        { "29:Hoa nở rực rỡ hết rồi! Thu hoạch nốt những chậu còn lại thôi nào.", "Every pot is in full bloom! Let's pick the rest of them." },
        { "30:CHÚC MỪNG BẠN LÊN CẤP 2! Nông trại đã mở khoá thêm nhiều tính năng mới!", "CONGRATULATIONS ON LEVEL 2! Your farm has unlocked lots of new features!" },
        { "31:Kho hạt giống đã hết rồi! Hãy mở Cửa Hàng để mua thêm hạt giống mới nhé!", "You're out of seeds! Open the Shop to buy some fresh new ones." },
        { "32:Chào mừng đến Cửa Hàng! Nông trại vừa mở khoá hạt Bắp Cải tươi ngon. Hãy mua một ít về gieo trồng nhé!", "Welcome to the Shop! Your farm just unlocked crisp Cabbage seeds. Buy a few and plant them!" },
        { "33:Bấm dấu ＋ để chọn đủ 8 hạt Bắp Cải rồi bấm Mua nhé!", "Tap ＋ to pick 8 Cabbage seeds, then tap Buy!" },
        { "34:Đã mua đủ hạt giống rồi! Giờ bấm nút đóng để quay về nông trại nào.", "You've got all the seeds you need! Now tap close to head back to the farm." },
        { "35:Hạt bắp cải đã về kho! Giờ hãy gieo những hạt bắp cải tươi xanh xuống các ô ruộng nhé!", "The cabbage seeds are in your storage! Now sow those fresh green seeds in your plots." },
        { "36:Tuyệt vời! Ngoài trồng trọt, nông trại còn nuôi những chú gà đẻ trứng đáng yêu. Hãy cùng chăm sóc đàn gà nào!", "Wonderful! Besides crops, your farm keeps adorable egg-laying chickens. Let's look after them!" },
        { "37:Chạm vào chuồng gà để xem đàn gà nào!", "Tap the chicken pen to see your flock!" },
        { "38:Kéo bao thóc vào chuồng để cho các chú gà ăn no nhé!", "Drag the feed sack into the pen so your chickens can eat their fill!" },
        { "39:Đàn gà đang ăn rồi! Dùng kim cương để gà đẻ trứng ngay nhé!", "Your chickens are eating! Use gems to get their eggs right away." },
        { "40:Trứng gà tươi ngon đã sẵn sàng! Kéo giỏ thu hoạch trứng nào!", "Fresh eggs are ready! Drag the basket over to collect them." },

        // -- Ten don hang (A) - Bo hoa, Bua com, Bep nha hang, Chuyen hang, Chuong, Com, Gio --
        { "Bó hoa chúc mau khỏi ốm", "Get Well Soon Bouquet" },
        { "Bó hoa cảm ơn hàng xóm", "Thank-You Bouquet" },
        { "Bó hoa hẹn hò lần đầu", "First Date Bouquet" },
        { "Bó hoa mừng em Sóc đạt giải", "Bouquet for Squirrel's Prize" },
        { "Bó hoa mừng khai trương", "Grand Opening Bouquet" },
        { "Bó hoa mừng nhà Nai tân gia", "Housewarming Bouquet for the Deers" },
        { "Bó hoa mừng sinh nhật", "Birthday Bouquet" },
        { "Bó hoa ngày của mẹ", "Mother's Day Bouquet" },
        { "Bó hoa ngày kỷ niệm cưới", "Wedding Anniversary Bouquet" },
        { "Bó hoa tiễn bạn đi xa", "Farewell Bouquet for a Friend" },
        { "Bó hoa tặng bác sĩ thú y", "Bouquet for the Vet" },
        { "Bó hoa tặng bác đưa thư", "Bouquet for the Postman" },
        { "Bó hoa tặng cô giáo", "Bouquet for the Teacher" },
        { "Bó hoa tặng mẹ", "Bouquet for Mum" },
        { "Bó hoa tặng người thắng cuộc", "Bouquet for the Winner" },
        { "Bó hoa xin lỗi", "Sorry Bouquet" },
        { "Bữa cơm bà cháu", "Grandma and Me Dinner" },
        { "Bữa cơm mừng con biết đi", "First Steps Family Meal" },
        { "Bữa cơm mừng lợp lại mái nhà", "New Roof Family Meal" },
        { "Bữa cơm ngày gió mùa", "Monsoon Day Meal" },
        { "Bữa cơm ngày mưa", "Rainy Day Meal" },
        { "Bữa cơm nhà anh Nai", "Dinner at Deer's House" },
        { "Bữa cơm nhà bác Heo", "Dinner at Uncle Pig's" },
        { "Bữa cơm nhà cô Vịt", "Dinner at Miss Duck's" },
        { "Bữa cơm nhà cậu Cún", "Dinner at Puppy's House" },
        { "Bữa cơm sau buổi cày", "After-Ploughing Meal" },
        { "Bữa cơm sau cơn mưa rào", "Meal After the Downpour" },
        { "Bữa cơm thợ gặt", "Harvesters' Meal" },
        { "Bữa cơm thợ xây", "Builders' Meal" },
        { "Bữa cơm đoàn viên", "Family Reunion Meal" },
        { "Bữa sáng nhà Thỏ", "Bunny Family Breakfast" },
        { "Bữa tiệc dưới gốc đa", "Feast Under the Old Banyan" },
        { "Bữa tiệc dưới ánh đèn lồng", "Lantern-Light Feast" },
        { "Bữa tiệc mừng bé Nhím vào đội", "Party for Little Hedgehog's Team" },
        { "Bữa tiệc mừng cầu vồng sau mưa", "Rainbow After the Rain Feast" },
        { "Bữa tiệc mừng mùa hoa nở rộ", "Blossom Season Feast" },
        { "Bữa tiệc đêm hội làng", "Village Festival Night Feast" },
        { "Bữa tiệc đêm rằm tháng Tám", "Full Moon Festival Feast" },
        { "Bữa trưa vội của bác Trâu", "Uncle Buffalo's Quick Lunch" },
        { "Bếp nhà hàng Bốn Mùa", "Four Seasons Kitchen" },
        { "Bếp nhà hàng Gác Chuông", "Bell Tower Kitchen" },
        { "Bếp nhà hàng Hoàng Hôn", "Sunset Kitchen" },
        { "Bếp nhà hàng Mây Trắng", "White Cloud Kitchen" },
        { "Bếp nhà hàng Ngọn Đồi", "Hilltop Kitchen" },
        { "Bếp nhà hàng Rừng Thông", "Pine Forest Kitchen" },
        { "Bếp nhà hàng Sao Mai", "Morning Star Kitchen" },
        { "Bếp nhà hàng Suối Reo", "Brookside Kitchen" },
        { "Bếp nhà hàng Trăng Non", "Crescent Moon Kitchen" },
        { "Bếp quán Gió Đồng", "Meadow Breeze Kitchen" },
        { "Bếp quán Lửa Hồng", "Warm Hearth Kitchen" },
        { "Bếp trưởng quán Hạt Dẻ", "Chestnut Diner Head Chef" },
        { "Chuyến hàng cho làng bên", "Delivery to the Next Village" },
        { "Chuyến hàng gửi tàu hoả", "Shipment for the Train" },
        { "Chuyến hàng lên núi", "Delivery Up the Mountain" },
        { "Chuyến hàng lên tỉnh", "Delivery to the City" },
        { "Chuyến hàng ra cảng", "Delivery to the Harbour" },
        { "Chuyến hàng theo đoàn", "Convoy Shipment" },
        { "Chuyến hàng vượt đèo", "Over-the-Pass Delivery" },
        { "Chuyến hàng đi chợ huyện", "Delivery to the County Market" },
        { "Chuyến hàng đêm", "Night Delivery" },
        { "Chuyến hàng đường xa", "Long-Haul Delivery" },
        { "Chuyến xe thồ đầu ngày", "First Cart of the Day" },
        { "Chuồng bê con nhà bác Voi", "Uncle Elephant's Calf Pen" },
        { "Chuồng bò bác Trâu cần tiếp tế", "Uncle Buffalo's Cow Pen Needs Feed" },
        { "Chuồng bò cuối xóm", "Cow Pen Down the Lane" },
        { "Chuồng cừu nhà Thỏ", "The Bunnies' Sheep Pen" },
        { "Chuồng dê trên sườn đồi", "Goat Pen on the Hillside" },
        { "Chuồng gà làng bên", "Next Village Chicken Pen" },
        { "Chuồng gà mái đẻ nhà Sóc", "Squirrel's Laying-Hen Pen" },
        { "Chuồng gà nhà cô Nai", "Miss Deer's Chicken Pen" },
        { "Chuồng heo con mới tách mẹ", "Pen of Newly Weaned Piglets" },
        { "Chuồng lợn mán nhà Nhím", "Hedgehog's Highland Pig Pen" },
        { "Chuồng ngan nhà Rùa", "Turtle's Muscovy Duck Pen" },
        { "Chuồng ngựa nhà Cáo", "Fox's Horse Stable" },
        { "Cơm chiều bên bếp lửa", "Fireside Evening Meal" },
        { "Cơm chiều nhà Gấu", "Evening Meal at the Bears'" },
        { "Cơm chiều nhà chị Ngỗng", "Evening Meal at Miss Goose's" },
        { "Cơm dẻo canh ngọt", "Soft Rice and Sweet Soup" },
        { "Cơm hộp cho bố đi làm", "Lunchbox for Dad at Work" },
        { "Cơm nhà, rau vườn", "Home Cooked Garden Meal" },
        { "Cơm nắm mang ra đồng", "Rice Balls for the Field" },
        { "Cơm trưa nhà bác Ngan", "Lunch at Uncle Muscovy's" },
        { "Cơm tối muộn nhà bác Bò", "Late Supper at Uncle Cow's" },
        { "Cơm tối nhà cô Cừu", "Supper at Miss Sheep's" },
        { "Giỏ củ quả nhà Chuột", "Mouse's Veggie Basket" },
        { "Giỏ hoa bàn tiệc", "Banquet Flower Basket" },
        { "Giỏ hoa bên cửa sổ", "Windowsill Flower Basket" },
        { "Giỏ hoa cho lớp học vẽ", "Flower Basket for the Art Class" },
        { "Giỏ hoa cho nhà nguyện nhỏ", "Flower Basket for the Little Chapel" },
        { "Giỏ hoa cho phòng khám", "Flower Basket for the Clinic" },
        { "Giỏ hoa cho quán trà Bà Rùa", "Flowers for Granny Turtle's Tea House" },
        { "Giỏ hoa cho đám rước đèn", "Lantern Parade Flowers" },
        { "Giỏ hoa gửi bưu điện", "Post Office Flowers" },
        { "Giỏ hoa gửi lên tỉnh", "Flowers for the City" },
        { "Giỏ hoa mừng em bé chào đời", "New Baby Flower Basket" },
        { "Giỏ hoa ngày lễ", "Holiday Flower Basket" },
        { "Giỏ hoa treo hiên nhà", "Hanging Porch Flower Basket" },
        { "Giỏ hoa đón khách phương xa", "Welcome Basket for Faraway Guests" },
        { "Giỏ hoa đặt bàn thờ", "Flower Basket for the Altar" },
        { "Giỏ rau cho bà ngoại", "Veggie Basket for Grandma" },
        { "Giỏ rau cho lớp mẫu giáo", "Veggie Basket for the Nursery" },

        // -- Ten don hang (B) - Ganh hang, Hang cho, Hoa, Khach, Lien hoan, Mam com, Nong trai, Quan --
        { "Gánh hàng bà Ngỗng", "Granny Goose's Market Load" },
        { "Gánh hàng chiều muộn", "Late Afternoon Market Load" },
        { "Gánh hàng của bà cụ Rùa", "Old Granny Turtle's Market Load" },
        { "Gánh hàng mưa phùn", "Drizzly Day Market Load" },
        { "Gánh hàng ngày nắng gắt", "Scorching Day Market Load" },
        { "Gánh hàng qua cầu tre", "Bamboo Bridge Market Load" },
        { "Gánh hàng qua đò", "Ferry Market Load" },
        { "Gánh hàng ra bến", "Market Load to the Dock" },
        { "Gánh hàng rong", "Street Vendor's Load" },
        { "Gánh hàng sương sớm", "Misty Morning Market Load" },
        { "Gánh hàng theo mẹ", "Market Load with Mum" },
        { "Gánh hàng đội mưa", "Market Load in the Rain" },
        { "Hàng cho chợ nổi", "Floating Market Goods" },
        { "Hàng cho chợ phiên vùng cao", "Goods for the Highland Fair" },
        { "Hàng cho chợ ven sông", "Goods for the Riverside Market" },
        { "Hàng cho chợ đầu mối", "Goods for the Wholesale Market" },
        { "Hàng cho hội chợ mùa gặt", "Goods for the Harvest Fair" },
        { "Hàng cho phiên chợ Tết", "Goods for the New Year Market" },
        { "Hàng cho phiên chợ cuối năm", "Goods for the Year-End Market" },
        { "Hàng cho quầy hợp tác xã", "Goods for the Co-op Stall" },
        { "Hàng chợ phiên", "Market Fair Goods" },
        { "Hàng gửi tàu sớm", "Early Train Goods" },
        { "Hàng gửi xe khách", "Goods for the Coach" },
        { "Hoa cho buổi hoà nhạc làng", "Flowers for the Village Concert" },
        { "Hoa cho gian hàng chợ phiên", "Flowers for the Market Fair Stall" },
        { "Hoa cho hiệu ảnh đầu làng", "Flowers for the Village Photo Shop" },
        { "Hoa cho lễ hội mùa xuân", "Flowers for the Spring Festival" },
        { "Hoa cho lễ tốt nghiệp", "Flowers for Graduation Day" },
        { "Hoa cho quán cà phê Góc Phố", "Flowers for Street Corner Cafe" },
        { "Hoa cho tiệm bánh Cô Sóc", "Flowers for Miss Squirrel's Bakery" },
        { "Hoa cho tiệm cắt tóc Chị Mèo", "Flowers for Miss Cat's Salon" },
        { "Hoa cho tiệm ảnh cưới Ánh Trăng", "Flowers for Moonlight Wedding Studio" },
        { "Hoa cài áo cô dâu", "Bride's Corsage" },
        { "Hoa cưới nhà Thỏ", "Bunny Wedding Flowers" },
        { "Hoa kết cổng cưới", "Wedding Arch Flowers" },
        { "Hoa kết vòng đội đầu", "Flower Crown Order" },
        { "Hoa trang trí sân khấu hội làng", "Stage Flowers for the Village Fair" },
        { "Hoa trang trí xe hoa", "Flowers for the Wedding Car" },
        { "Khách bí ẩn đặt hàng đêm", "Mystery Guest's Night Order" },
        { "Khách lạ trả tiền trước", "Stranger Paying Up Front" },
        { "Khách phương xa trả hậu", "Faraway Guest Paying Generously" },
        { "Khách quen đặt gấp", "Regular's Rush Order" },
        { "Khách quý từ kinh thành", "Honoured Guest from the Capital" },
        { "Khách quý đi cùng đoàn sứ", "Honoured Guest with the Envoy" },
        { "Khách quý đặt riêng", "VIP Private Order" },
        { "Khách quý đặt trọn gói", "Honoured Guest's Full Package" },
        { "Khách sang trọng đặt hàng hiếm", "Fancy Guest Wants Rare Goods" },
        { "Khách sang đặt vội", "Fancy Guest in a Hurry" },
        { "Khách sộp đặt nguyên lô", "Big Spender Buys the Lot" },
        { "Liên hoan cuối mùa", "End of Season Party" },
        { "Liên hoan hội đua thuyền", "Boat Race Party" },
        { "Liên hoan mừng cầu mới", "New Bridge Party" },
        { "Liên hoan mừng giếng làng có nước", "Village Well Party" },
        { "Liên hoan mừng kho thóc đầy", "Full Granary Party" },
        { "Liên hoan mừng lúa vào bồ", "Rice in the Barn Party" },
        { "Liên hoan mừng máy xay về làng", "New Feed Mill Party" },
        { "Liên hoan mừng vụ đông thắng lợi", "Winter Crop Success Party" },
        { "Liên hoan mừng đàn gà nở", "Chicks Hatching Party" },
        { "Liên hoan mừng đường mới đổ", "New Road Party" },
        { "Liên hoan mừng được mùa", "Bumper Harvest Party" },
        { "Liên hoan đội gặt", "Harvest Crew Party" },
        { "Mâm cơm cuối tuần", "Weekend Family Spread" },
        { "Mâm cơm ngày giỗ", "Memorial Day Spread" },
        { "Mâm cơm ngày mùa", "Harvest Season Spread" },
        { "Mâm cơm ngày rằm", "Full Moon Day Spread" },
        { "Mâm cơm ngày trăng tròn", "Full Moon Night Spread" },
        { "Mâm cơm ngày trở trời", "Chilly Weather Spread" },
        { "Mâm cơm tiễn khách", "Farewell Feast Spread" },
        { "Mâm cơm đãi ông bà", "Spread for Grandparents" },
        { "Nhà hàng Vườn Trăng", "Moon Garden Restaurant" },
        { "Nhà hàng Đồng Xanh", "Green Field Restaurant" },
        { "Nhà kho trang trại Sáng Sớm", "Early Morning Farm Warehouse" },
        { "Nông trại Bình Minh cần hàng", "Sunrise Farm Needs Goods" },
        { "Nông trại Bốn Mùa gọi hàng", "Four Seasons Farm Is Calling" },
        { "Nông trại Bờ Suối", "Creekside Farm" },
        { "Nông trại Chân Đồi", "Hillfoot Farm" },
        { "Nông trại Cỏ Non", "Fresh Grass Farm" },
        { "Nông trại Hạt Sương", "Dewdrop Farm" },
        { "Nông trại Mưa Rào", "Rainshower Farm" },
        { "Nông trại Nắng Vàng", "Golden Sun Farm" },
        { "Nông trại Sao Đêm", "Night Star Farm" },
        { "Nông trại Sương Mai", "Morning Mist Farm" },
        { "Nông trại Đồi Cỏ cần hàng", "Grassy Hill Farm Needs Goods" },
        { "Nồi canh chiều nhà Mèo", "Evening Soup Pot at the Cats'" },
        { "Nồi canh chiều thứ Bảy", "Saturday Evening Soup Pot" },
        { "Nồi canh cà chua chiều muộn", "Late Afternoon Tomato Soup" },
        { "Nồi canh rau tập tàng", "Mixed Garden Greens Soup" },
        { "Nồi cháo cho bé Sóc", "Porridge for Squirrel" },
        { "Quán bánh Cô Thỏ", "Miss Bunny's Cake Shop" },
        { "Quán bún Cô Vịt", "Miss Duck's Noodle Shop" },
        { "Quán canh chua Dì Ngỗng", "Auntie Goose's Sour Soup Shop" },
        { "Quán chay Sen Nở", "Lotus Bloom Veggie Diner" },
        { "Quán cháo khuya Bác Cú", "Uncle Owl's Late-Night Porridge" },
        { "Quán cơm Bà Tám", "Granny Tam's Rice Diner" },
        { "Quán cơm bình dân đầu chợ", "Market-Gate Home Cooking" },
        { "Quán cơm gà Chị Mèo", "Miss Cat's Chicken Rice" },
        { "Quán cơm niêu Bác Trâu", "Uncle Buffalo's Clay Pot Rice" },
        { "Quán cơm thợ mỏ", "Miners' Rice Canteen" },
        { "Quán cỗ chay Bà Rùa", "Granny Turtle Veggie Feast" },
        { "Quán lẩu Nhà Gấu", "Bear Family Hotpot" },
        { "Quán mì Bến Đò", "Ferry Noodle Shop" },
        { "Quán nướng Ba Con Sóc", "Three Squirrels Grill" },
        { "Quán xào Chú Chuột", "Uncle Mouse's Stir-Fry Shop" },
        { "Quán ăn Bên Cầu", "Bridgeside Eatery" },
        { "Quán ăn khuya Xóm Chài", "Fishing Village Night Diner" },
        { "Quán ăn sáng Ngã Ba", "Crossroads Breakfast Shop" },
        { "Quán ăn vặt Cổng Trường", "School Gate Snack Shop" },
        { "Rổ rau nhà bên", "Neighbour Veggie Basket" },
        { "Rổ rau sau vườn", "Backyard Veggie Basket" },
        { "Rổ rau tươi buổi sớm", "Fresh Morning Veggie Basket" },

        // -- Ten don hang (C) - Sap hang, Tiec, Trai, Don, Dat -----------
        { "Sạp hàng chợ Tây", "West Market Stall" },
        { "Sạp hàng cuối chợ", "Far End Market Stall" },
        { "Sạp hàng dưới gốc đa", "Stall Under the Banyan Tree" },
        { "Sạp hàng góc chợ Đông", "East Market Corner Stall" },
        { "Sạp hàng nhà Chuột", "The Mouse Family Stall" },
        { "Sạp hàng nhà bác Heo", "Uncle Pig's Stall" },
        { "Sạp hàng nhà chị Cừu", "Miss Sheep's Stall" },
        { "Sạp hàng phiên chợ rằm", "Full Moon Fair Stall" },
        { "Sạp hàng phiên đầu tháng", "First-of-the-Month Fair Stall" },
        { "Sạp rau chợ sớm", "Early Veggie Stall" },
        { "Sạp rau củ nhà Thỏ", "The Bunnies' Veggie Stall" },
        { "Tiệc chia tay chú Ngựa lên tỉnh", "Farewell Party for Horse" },
        { "Tiệc cưới nhà Sóc", "Squirrel Wedding Feast" },
        { "Tiệc mừng anh Cáo lấy vợ", "Fox's Wedding Party" },
        { "Tiệc mừng bác Gấu khỏi ốm", "Uncle Bear's Get-Well Party" },
        { "Tiệc mừng bác Heo trúng mùa", "Uncle Pig's Bumper Harvest Party" },
        { "Tiệc mừng bác Trâu về hưu", "Uncle Buffalo's Retirement Party" },
        { "Tiệc mừng bé Chuột biết đọc", "Little Mouse Can Read Party" },
        { "Tiệc mừng bé Mèo vào lớp một", "Little Cat's First Day of School" },
        { "Tiệc mừng chợ mới khai trương", "New Market Opening Party" },
        { "Tiệc mừng cô Cừu thắng hội thi", "Miss Sheep's Contest Win Party" },
        { "Tiệc mừng cụ Voi tròn trăm tuổi", "Great-Granny Elephant Turns 100" },
        { "Tiệc mừng ngày hội hoa xuân", "Spring Flower Festival Party" },
        { "Tiệc mừng ngày lập làng", "Village Founding Day Party" },
        { "Tiệc mừng nhà Nai dựng cổng", "The Deers' New Gate Party" },
        { "Tiệc mừng nhà Ngỗng đón dâu", "The Geese Welcome a Bride" },
        { "Tiệc mừng nhà Sóc lợp ngói mới", "The Squirrels' New Roof Party" },
        { "Tiệc mừng nhà Thỏ sinh đôi", "The Bunnies' Twins Party" },
        { "Tiệc mừng nhà mới", "Housewarming Party" },
        { "Tiệc mừng thuyền về bến", "Boats Home Safe Party" },
        { "Tiệc mừng thọ cụ Rùa", "Granny Turtle's Birthday Feast" },
        { "Tiệc mừng trường làng khai giảng", "Village School Opening Party" },
        { "Tiệc mừng đàn bò về chuồng đủ", "All the Cows Home Party" },
        { "Tiệc mừng đội bóng làng vô địch", "Village Team Championship Party" },
        { "Tiệc thôi nôi bé Cún", "Little Puppy's First Birthday" },
        { "Tiệc tất niên xóm Đông", "East Hamlet Year-End Party" },
        { "Tiệc đầy tháng bé Vịt", "Little Duck's One-Month Party" },
        { "Trại bò nghé nhà Trâu con", "Little Buffalo's Calf Ranch" },
        { "Trại bò sữa Cô Mèo", "Miss Cat's Dairy Farm" },
        { "Trại bò thịt Đồng Xa", "Far Field Cattle Ranch" },
        { "Trại chăn nuôi hợp tác xã", "Co-op Livestock Farm" },
        { "Trại cừu lông dài", "Longwool Sheep Farm" },
        { "Trại dê núi bác Sơn Dương", "Uncle Goat's Mountain Goat Farm" },
        { "Trại gia cầm đầu làng", "Village Gate Poultry Farm" },
        { "Trại gia súc bên kia đồi", "Livestock Farm Over the Hill" },
        { "Trại giống nhà bác Ngỗng", "Uncle Goose's Breeding Farm" },
        { "Trại gà nhà Vịt cần hàng", "The Ducks' Chicken Farm Needs Goods" },
        { "Trại gà ta nhà chú Cún", "Puppy's Free-Range Chicken Farm" },
        { "Trại gà tre nhà Nhím", "Hedgehog's Bantam Chicken Farm" },
        { "Trại heo nhà Gấu đặt hàng", "The Bears' Pig Farm Orders" },
        { "Trại lợn nái nhà Bò", "The Cows' Sow Farm" },
        { "Trại ong bác Ngựa", "Uncle Horse's Bee Farm" },
        { "Trại sữa Gió Mát", "Cool Breeze Dairy" },
        { "Trại thỏ giống miền ngược", "Highland Rabbit Breeding Farm" },
        { "Trại thỏ nhà bé Chuột", "Little Mouse's Rabbit Farm" },
        { "Trại vịt bên sông", "Riverside Duck Farm" },
        { "Trại vịt cỏ ven đầm", "Marshside Duck Farm" },
        { "Trại vịt đẻ nhà chị Ngỗng", "Miss Goose's Laying Duck Farm" },
        { "Đơn bếp bệnh viện làng", "Village Hospital Kitchen Order" },
        { "Đơn bếp chợ đêm", "Night Market Order" },
        { "Đơn bếp hội làng", "Village Fair Order" },
        { "Đơn bếp lễ hội mùa gặt", "Harvest Festival Kitchen Order" },
        { "Đơn bếp tiệc cưới", "Wedding Kitchen Order" },
        { "Đơn bếp trường nội trú", "Boarding School Kitchen Order" },
        { "Đơn bếp trại hè", "Summer Camp Order" },
        { "Đơn bếp đội cứu hộ", "Rescue Team Kitchen Order" },
        { "Đơn gấp cho bếp bệnh viện", "Rush Order for the Hospital Kitchen" },
        { "Đơn gấp cho lễ khai trương sáng mai", "Rush Order for Tomorrow's Opening" },
        { "Đơn gấp cho tiệc chia tay", "Rush Order for a Farewell Party" },
        { "Đơn gấp cho tiệc tối nay", "Rush Order for Tonight's Party" },
        { "Đơn gấp cho đoàn hát rong", "Rush Order: Travelling Singers" },
        { "Đơn gấp cho đoàn làm phim", "Rush Order for the Film Crew" },
        { "Đơn gấp cứu bếp cháy hàng", "Rush Order: Kitchen Sold Out" },
        { "Đơn gấp trước giờ tàu chạy", "Rush Order Before the Train Leaves" },
        { "Đơn gấp — bếp trưởng gọi ba lần", "Rush Order — Chef Called Three Times" },
        { "Đơn gấp — thiếu hàng đột xuất", "Rush Order — Sudden Shortage" },
        { "Đơn gấp — trả hậu", "Rush Order — Pays Well" },
        { "Đơn hoả tốc chuyến tàu 5 giờ", "Express Order for the 5 O'Clock Train" },
        { "Đơn hoả tốc gửi lên tỉnh", "Express Order to the City" },
        { "Đơn hoả tốc trong ngày", "Same-Day Express Order" },
        { "Đơn hoả tốc trước cơn bão", "Express Order Before the Storm" },
        { "Đơn hoả tốc trước giờ đóng chợ", "Express Order Before Market Closes" },
        { "Đơn hoả tốc — xe đã chờ ngoài cổng", "Express Order — Cart Waiting at the Gate" },
        { "Đơn khẩn cấp — bù cho chuyến hỏng", "Urgent Order — Replacing a Lost Load" },
        { "Đơn khẩn của quan huyện", "Urgent Order from the Magistrate" },
        { "Đơn khẩn — làng bên mất mùa", "Urgent — Next Village Crop Lost" },
        { "Đơn quán Cô Ba", "Miss Ba's Diner Order" },
        { "Đơn quán nhậu Chú Cáo", "Uncle Fox's Tavern Order" },
        { "Đơn quán phở Ông Gấu", "Grandpa Bear's Pho Shop Order" },
        { "Đơn quán ăn ga tàu", "Train Station Eatery Order" },
        { "Đơn ưu tiên của hội đồng làng", "Priority Order from the Village Council" },
        { "Đơn ưu tiên của nhà buôn lớn", "Priority Order from a Big Trader" },
        { "Đơn ưu tiên — trả bằng vàng ròng", "Priority Order — Paid in Pure Gold" },
        { "Đặt gấp cho đoàn khách", "Rush Booking for a Tour Group" },
        { "Đặt riêng cho nhà giàu xóm Trên", "Private Order for the Uptown Rich" },
        { "Đặt riêng của chủ tiệm lớn", "Private Order from a Big Shop Owner" },
        { "Đặt riêng — giữ kín tên khách", "Private Order — Name Withheld" },
        { "Đặt riêng — không hỏi giá", "Private Order — Price No Object" },
        { "Đặt riêng, trả gấp đôi", "Private Order, Pays Double" },
        { "Đặt vội cho hội thi nấu ăn", "Quick Order for the Cooking Contest" },
        { "Đặt vội cho lễ cầu mưa", "Quick Order: Rain Ceremony" },
        { "Đặt vội cho đoàn cứu trợ", "Quick Order for the Relief Team" },
        { "Đặt vội cho đám cưới chiều mai", "Quick Order for Tomorrow's Wedding" },
        { "Đặt vội trước giờ chợ tan", "Quick Order Before Market Closes" },
        // ══════════════════════════════════════════════════════════════════
        // ĐỢT 2 (06/09/2026) — bổ sung chuỗi CÒN SÓT khi bấm English.
        // Nguồn: quét toàn bộ ScriptableObject (.asset) + code UI runtime.
        // Khoá chép NGUYÊN VĂN từ asset/code, kể cả chỗ gõ sai dấu — sửa chính
        // tả trong asset thì phải sửa khoá ở đây theo.
        // ══════════════════════════════════════════════════════════════════

        // -- Ten vat pham / mon an / trang tri (tu file .asset) --
        { "Bá»t gáº¡o", "Rice Flour" },
        { "Bình Tưới Hoa", "Flower Watering Can" },
        { "Bí Đỏ · Lúa · Mía", "Pumpkin · Rice · Sugarcane" },
        { "Bí Đỏ · Thịt Heo", "Pumpkin · Pork" },
        { "Bò hầm cà rót", "Beef and Carrot Stew" },
        { "Bù nhìn", "Scarecrow" },
        { "Bảng Hiệu", "Signpost" },
        { "Bắp Cải · Cà Rốt", "Cabbage · Carrot" },
        { "Bắp cải · Chanh", "Cabbage · Lemon" },
        { "Bắp cải · Nấm", "Cabbage · Mushroom" },
        { "Chân Hoa", "Flower Stand" },
        { "Chú Lùn Sân Vườn", "Garden Gnome" },
        { "Chạm vào ô lúa chín để thu hoạch nào!", "Tap the ripe rice plots to harvest them!" },
        { "Chậu Bạc", "Silver Pot" },
        { "Chậu Cây Thú", "Topiary Pot" },
        { "Chậu Vàng", "Golden Pot" },
        { "Chậu Đá Quý", "Gem Pot" },
        { "Chậu Đất", "Clay Pot" },
        { "Cà Chua · Cà Rốt · Rau Thơm", "Tomato · Carrot · Herbs" },
        { "Cám cho bò sữa", "Dairy Cow Feed" },
        { "Cám cho gà", "Chicken Feed" },
        { "Cám cho heo", "Pig Feed" },
        { "Cả ruộng chín vàng rồi! Quẹt liềm thu hoạch nốt những ô còn lại nào.", "The whole field is golden! Swipe the sickle to harvest the rest." },
        { "Cỏ trộn cho bò", "Cattle Feed Mix" },
        { "Cối Xoay Gió", "Windmill" },
        { "Cột Đèn", "Lamp Post" },
        { "Dưa Hấu · Mía", "Watermelon · Sugarcane" },
        { "Dưa Hấu · Rau Thơm", "Watermelon · Herbs" },
        { "Dưa Hấu · Thịt Bò · Rau Thơm", "Watermelon · Beef · Herbs" },
        { "Ghế Hoa", "Flower Bench" },
        { "Gieo nốt hạt hướng dương vào những chậu còn trống nhé!", "Sow the last sunflower seeds in the empty pots!" },
        { "Giá Bán Rau", "Veggie Stand" },
        { "Giếng", "Well" },
        { "Giỏi lắm! Gieo nốt cho kín cả 8 ô ruộng nhé — bàn tay sẽ chỉ ô còn trống cho bạn.", "Nicely done! Fill all 8 plots — the hand will point out the empty ones." },
        { "Gà nướng lu", "Clay Jar Roast Chicken" },
        { "Gạo", "Rice" },
        { "Heo Thần Tài", "Lucky Piggy" },
        { "Heo Vui Vẻ", "Happy Piggy" },
        { "Hoa nở rực rỡ hết rồi! Thu hoạch nốt những chậu còn lại thôi nào.", "Every flower is in full bloom! Harvest the last pots now." },
        { "Hồ Đá", "Stone Pond" },
        { "Khoai Tây · Cà Rốt", "Potato · Carrot" },
        { "Khoai Tây · Nấm", "Potato · Mushroom" },
        { "Khoai tây · Cà rốt · Thịt heo", "Potato · Carrot · Pork" },
        { "Kéo bao cám vào chuồng để đàn gà ăn no nhé!", "Drag the feed sack into the pen so the chickens can eat!" },
        { "Lúa · Bắp Cải", "Rice · Cabbage" },
        { "Lúa · Thịt bò · Chanh · Ớt", "Rice · Beef · Lemon · Chili" },
        { "Lúa · Trứng gà", "Rice · Egg" },
        { "Máy Phô Mai", "Cheese Maker" },
        { "Máy Xay Bột", "Flour Mill" },
        { "Máy Ép Mía", "Sugarcane Press" },
        { "Mía · Chanh", "Sugarcane · Lemon" },
        { "Ngô · Lúa · Mía", "Corn · Rice · Sugarcane" },
        { "Ngô · Lúa · Trứng", "Corn · Rice · Egg" },
        { "Ngô · Mía", "Corn · Sugarcane" },
        { "Ngô · Nấm · Trứng gà", "Corn · Mushroom · Egg" },
        { "Ngô · Trứng", "Corn · Egg" },
        { "Nhà Dân 1", "Village House 1" },
        { "Nhà Dân 2", "Village House 2" },
        { "Nhà Dân 3", "Village House 3" },
        { "Nhà Dân 4", "Village House 4" },
        { "Nhà Dân 5", "Village House 5" },
        { "NÆ°á»c mía ép", "Sugarcane Juice" },
        { "Nấm · Cà Chua · Rau Thơm", "Mushroom · Tomato · Herbs" },
        { "Nấm · Rau", "Mushroom · Greens" },
        { "Nấm · Thịt bò", "Mushroom · Beef" },
        { "Rơm Hoa", "Flower Haystack" },
        { "Salad nấm rau", "Mushroom Garden Salad" },
        { "Súp ngo nấm", "Corn Mushroom Soup" },
        { "Thịt Bò · Bí Đỏ · Khoai Tây", "Beef · Pumpkin · Potato" },
        { "Thịt Gà · Bắp Cải", "Chicken · Cabbage" },
        { "Thịt Gà · Nấm · Cà Rốt", "Chicken · Mushroom · Carrot" },
        { "Thịt bò · Cà rốt", "Beef · Carrot" },
        { "Thịt bò · Tiêu", "Beef · Pepper" },
        { "Thịt gà · Mía", "Chicken · Sugarcane" },
        { "Thịt gà · Ớt", "Chicken · Chili" },
        { "Thịt heo · Cà chua · Chanh · Ớt", "Pork · Tomato · Lemon · Chili" },
        { "Thịt heo · Rau", "Pork · Greens" },
        { "Trứng gà · Cà chua", "Egg · Tomato" },
        { "Trứng gà · Thịt bò · Cà chua", "Egg · Beef · Tomato" },
        { "Trứng óp la bò né", "Sizzling Beef and Egg" },
        { "Vòng Hoa", "Flower Wreath" },
        { "Vịt Vui Vẻ", "Happy Ducky" },
        { "Đài Nước", "Fountain" },
        { "Đất Trồng", "Plot of Land" },

        // -- Ten nhiem vu / thanh tuu (tu file .asset) --
        { "Bậc thầy Nông trại — đạt L30", "Farm Master — reach L30" },
        { "Bếp trưởng — nấu 150 món", "Head Chef — cook 150 dishes" },
        { "Cho gà ăn 1 lần", "Feed the chickens 1 time" },
        { "Cho heo ăn 2 lần", "Feed the pigs 2 times" },
        { "Cho thú ăn 4 lần", "Feed the animals 4 times" },
        { "Cho vật nuôi ăn 2 lần", "Feed the animals 2 times" },
        { "Chế biến 100 sản phẩm", "Process 100 products" },
        { "Chế biến 12 sản phẩm", "Process 12 products" },
        { "Chế biến 15 sản phẩm", "Process 15 products" },
        { "Chế biến 18 sản phẩm", "Process 18 products" },
        { "Chế biến 20 sản phẩm", "Process 20 products" },
        { "Chế biến 21 sản phẩm", "Process 21 products" },
        { "Chế biến 24 sản phẩm", "Process 24 products" },
        { "Chế biến 27 sản phẩm", "Process 27 products" },
        { "Chế biến 3 sản phẩm", "Process 3 products" },
        { "Chế biến 30 sản phẩm", "Process 30 products" },
        { "Chế biến 33 sản phẩm", "Process 33 products" },
        { "Chế biến 36 sản phẩm", "Process 36 products" },
        { "Chế biến 39 sản phẩm", "Process 39 products" },
        { "Chế biến 40 sản phẩm", "Process 40 products" },
        { "Chế biến 42 sản phẩm", "Process 42 products" },
        { "Chế biến 45 sản phẩm", "Process 45 products" },
        { "Chế biến 48 sản phẩm", "Process 48 products" },
        { "Chế biến 51 sản phẩm", "Process 51 products" },
        { "Chế biến 54 sản phẩm", "Process 54 products" },
        { "Chế biến 57 sản phẩm", "Process 57 products" },
        { "Chế biến 6 sản phẩm", "Process 6 products" },
        { "Chế biến 60 sản phẩm", "Process 60 products" },
        { "Chế biến 63 sản phẩm", "Process 63 products" },
        { "Chế biến 66 sản phẩm", "Process 66 products" },
        { "Chế biến 69 sản phẩm", "Process 69 products" },
        { "Chế biến 70 sản phẩm", "Process 70 products" },
        { "Chế biến 72 sản phẩm", "Process 72 products" },
        { "Chế biến 75 sản phẩm", "Process 75 products" },
        { "Chế biến 78 sản phẩm", "Process 78 products" },
        { "Chế biến 8 sản phẩm", "Process 8 products" },
        { "Chế biến 81 sản phẩm", "Process 81 products" },
        { "Chế biến 84 sản phẩm", "Process 84 products" },
        { "Chế biến 87 sản phẩm", "Process 87 products" },
        { "Chế biến 9 sản phẩm", "Process 9 products" },
        { "Chế biến 90 sản phẩm", "Process 90 products" },
        { "Giao 1 Gà Xào Ớt", "Deliver 1 Chili Chicken" },
        { "Giao 1 Phở Bò Tái", "Deliver 1 Rare Beef Pho" },
        { "Giao 1 Trứng Chiên Cà Chua", "Deliver 1 Tomato Omelette" },
        { "Giao 1 món cơm chiên trứng", "Deliver 1 Egg Fried Rice" },
        { "Giao 1 đơn combo", "Deliver 1 combo orders" },
        { "Giao 1 đơn hàng", "Deliver 1 orders" },
        { "Giao 1 đơn thịt bò", "Deliver 1 beef order" },
        { "Giao 10 đơn combo", "Deliver 10 combo orders" },
        { "Giao 10 đơn hàng", "Deliver 10 orders" },
        { "Giao 12 đơn hàng", "Deliver 12 orders" },
        { "Giao 14 đơn hàng", "Deliver 14 orders" },
        { "Giao 16 đơn hàng", "Deliver 16 orders" },
        { "Giao 18 đơn hàng", "Deliver 18 orders" },
        { "Giao 2 đơn combo", "Deliver 2 combo orders" },
        { "Giao 2 đơn hàng", "Deliver 2 orders" },
        { "Giao 20 đơn combo", "Deliver 20 combo orders" },
        { "Giao 20 đơn hàng", "Deliver 20 orders" },
        { "Giao 22 đơn hàng", "Deliver 22 orders" },
        { "Giao 24 đơn hàng", "Deliver 24 orders" },
        { "Giao 26 đơn hàng", "Deliver 26 orders" },
        { "Giao 28 đơn hàng", "Deliver 28 orders" },
        { "Giao 3 đơn combo", "Deliver 3 combo orders" },
        { "Giao 3 đơn hàng", "Deliver 3 orders" },
        { "Giao 30 đơn hàng", "Deliver 30 orders" },
        { "Giao 32 đơn hàng", "Deliver 32 orders" },
        { "Giao 34 đơn hàng", "Deliver 34 orders" },
        { "Giao 35 đơn combo", "Deliver 35 combo orders" },
        { "Giao 36 đơn hàng", "Deliver 36 orders" },
        { "Giao 38 đơn hàng", "Deliver 38 orders" },
        { "Giao 40 đơn hàng", "Deliver 40 orders" },
        { "Giao 42 đơn hàng", "Deliver 42 orders" },
        { "Giao 44 đơn hàng", "Deliver 44 orders" },
        { "Giao 46 đơn hàng", "Deliver 46 orders" },
        { "Giao 48 đơn hàng", "Deliver 48 orders" },
        { "Giao 5 đơn combo", "Deliver 5 combo orders" },
        { "Giao 5 đơn hàng", "Deliver 5 orders" },
        { "Giao 50 đơn hàng", "Deliver 50 orders" },
        { "Giao 52 đơn hàng", "Deliver 52 orders" },
        { "Giao 54 đơn hàng", "Deliver 54 orders" },
        { "Giao 56 đơn hàng", "Deliver 56 orders" },
        { "Giao 58 đơn hàng", "Deliver 58 orders" },
        { "Giao 6 đơn hàng", "Deliver 6 orders" },
        { "Giao 60 đơn hàng", "Deliver 60 orders" },
        { "Giao 8 đơn hàng", "Deliver 8 orders" },
        { "Giao tổng cộng 20 đơn hàng", "Deliver 20 orders in total" },
        { "Hoàn thành 100 đơn", "Complete 100 orders" },
        { "Hoàn thành 150 đơn", "Complete 150 orders" },
        { "Hoàn thành 250 đơn", "Complete 250 orders" },
        { "Hoàn thành 350 đơn", "Complete 350 orders" },
        { "Hoàn thành 40 đơn", "Complete 40 orders" },
        { "Hoàn thành 450 đơn", "Complete 450 orders" },
        { "Hoàn thành 500 đơn", "Complete 500 orders" },
        { "Hoàn thành 60 đơn", "Complete 60 orders" },
        { "Khởi đầu vững — đạt L10", "Strong Start — reach L10" },
        { "Làm 3 phô mai", "Make 3 Cheese" },
        { "Mua 1 hạt giống", "Buy 1 seed" },
        { "Mua 1 hạt giống mới", "Buy 1 new seed" },
        { "Mua 3 hạt giống", "Buy 3 seeds" },
        { "Mua Máy Phô Mai", "Buy the Cheese Maker" },
        { "Mua Máy Xay Bột", "Buy the Flour Mill" },
        { "Mua Máy Ép Mía", "Buy the Sugarcane Press" },
        { "Mua chuồng bò", "Buy the Cow Pen" },
        { "Mua chuồng heo", "Buy the Pig Pen" },
        { "Mở rộng đất 1 khu", "Expand your land by 1 plot" },
        { "Người giao hàng — 50 đơn", "Delivery Star — 50 orders" },
        { "Nông dân cấp 10", "Farmer Level 10" },
        { "Nông dân cấp 100", "Farmer Level 100" },
        { "Nông dân cấp 11", "Farmer Level 11" },
        { "Nông dân cấp 12", "Farmer Level 12" },
        { "Nông dân cấp 13", "Farmer Level 13" },
        { "Nông dân cấp 14", "Farmer Level 14" },
        { "Nông dân cấp 15", "Farmer Level 15" },
        { "Nông dân cấp 16", "Farmer Level 16" },
        { "Nông dân cấp 17", "Farmer Level 17" },
        { "Nông dân cấp 18", "Farmer Level 18" },
        { "Nông dân cấp 19", "Farmer Level 19" },
        { "Nông dân cấp 2", "Farmer Level 2" },
        { "Nông dân cấp 20", "Farmer Level 20" },
        { "Nông dân cấp 21", "Farmer Level 21" },
        { "Nông dân cấp 22", "Farmer Level 22" },
        { "Nông dân cấp 23", "Farmer Level 23" },
        { "Nông dân cấp 24", "Farmer Level 24" },
        { "Nông dân cấp 25", "Farmer Level 25" },
        { "Nông dân cấp 26", "Farmer Level 26" },
        { "Nông dân cấp 27", "Farmer Level 27" },
        { "Nông dân cấp 28", "Farmer Level 28" },
        { "Nông dân cấp 29", "Farmer Level 29" },
        { "Nông dân cấp 3", "Farmer Level 3" },
        { "Nông dân cấp 30", "Farmer Level 30" },
        { "Nông dân cấp 31", "Farmer Level 31" },
        { "Nông dân cấp 32", "Farmer Level 32" },
        { "Nông dân cấp 33", "Farmer Level 33" },
        { "Nông dân cấp 34", "Farmer Level 34" },
        { "Nông dân cấp 35", "Farmer Level 35" },
        { "Nông dân cấp 36", "Farmer Level 36" },
        { "Nông dân cấp 37", "Farmer Level 37" },
        { "Nông dân cấp 38", "Farmer Level 38" },
        { "Nông dân cấp 39", "Farmer Level 39" },
        { "Nông dân cấp 4", "Farmer Level 4" },
        { "Nông dân cấp 40", "Farmer Level 40" },
        { "Nông dân cấp 41", "Farmer Level 41" },
        { "Nông dân cấp 42", "Farmer Level 42" },
        { "Nông dân cấp 43", "Farmer Level 43" },
        { "Nông dân cấp 44", "Farmer Level 44" },
        { "Nông dân cấp 45", "Farmer Level 45" },
        { "Nông dân cấp 46", "Farmer Level 46" },
        { "Nông dân cấp 47", "Farmer Level 47" },
        { "Nông dân cấp 48", "Farmer Level 48" },
        { "Nông dân cấp 49", "Farmer Level 49" },
        { "Nông dân cấp 5", "Farmer Level 5" },
        { "Nông dân cấp 50", "Farmer Level 50" },
        { "Nông dân cấp 51", "Farmer Level 51" },
        { "Nông dân cấp 52", "Farmer Level 52" },
        { "Nông dân cấp 53", "Farmer Level 53" },
        { "Nông dân cấp 54", "Farmer Level 54" },
        { "Nông dân cấp 55", "Farmer Level 55" },
        { "Nông dân cấp 56", "Farmer Level 56" },
        { "Nông dân cấp 57", "Farmer Level 57" },
        { "Nông dân cấp 58", "Farmer Level 58" },
        { "Nông dân cấp 59", "Farmer Level 59" },
        { "Nông dân cấp 6", "Farmer Level 6" },
        { "Nông dân cấp 60", "Farmer Level 60" },
        { "Nông dân cấp 61", "Farmer Level 61" },
        { "Nông dân cấp 62", "Farmer Level 62" },
        { "Nông dân cấp 63", "Farmer Level 63" },
        { "Nông dân cấp 64", "Farmer Level 64" },
        { "Nông dân cấp 65", "Farmer Level 65" },
        { "Nông dân cấp 66", "Farmer Level 66" },
        { "Nông dân cấp 67", "Farmer Level 67" },
        { "Nông dân cấp 68", "Farmer Level 68" },
        { "Nông dân cấp 69", "Farmer Level 69" },
        { "Nông dân cấp 7", "Farmer Level 7" },
        { "Nông dân cấp 70", "Farmer Level 70" },
        { "Nông dân cấp 71", "Farmer Level 71" },
        { "Nông dân cấp 72", "Farmer Level 72" },
        { "Nông dân cấp 73", "Farmer Level 73" },
        { "Nông dân cấp 74", "Farmer Level 74" },
        { "Nông dân cấp 75", "Farmer Level 75" },
        { "Nông dân cấp 76", "Farmer Level 76" },
        { "Nông dân cấp 77", "Farmer Level 77" },
        { "Nông dân cấp 78", "Farmer Level 78" },
        { "Nông dân cấp 79", "Farmer Level 79" },
        { "Nông dân cấp 8", "Farmer Level 8" },
        { "Nông dân cấp 80", "Farmer Level 80" },
        { "Nông dân cấp 81", "Farmer Level 81" },
        { "Nông dân cấp 82", "Farmer Level 82" },
        { "Nông dân cấp 83", "Farmer Level 83" },
        { "Nông dân cấp 84", "Farmer Level 84" },
        { "Nông dân cấp 85", "Farmer Level 85" },
        { "Nông dân cấp 86", "Farmer Level 86" },
        { "Nông dân cấp 87", "Farmer Level 87" },
        { "Nông dân cấp 88", "Farmer Level 88" },
        { "Nông dân cấp 89", "Farmer Level 89" },
        { "Nông dân cấp 9", "Farmer Level 9" },
        { "Nông dân cấp 90", "Farmer Level 90" },
        { "Nông dân cấp 91", "Farmer Level 91" },
        { "Nông dân cấp 92", "Farmer Level 92" },
        { "Nông dân cấp 93", "Farmer Level 93" },
        { "Nông dân cấp 94", "Farmer Level 94" },
        { "Nông dân cấp 95", "Farmer Level 95" },
        { "Nông dân cấp 96", "Farmer Level 96" },
        { "Nông dân cấp 97", "Farmer Level 97" },
        { "Nông dân cấp 98", "Farmer Level 98" },
        { "Nông dân cấp 99", "Farmer Level 99" },
        { "Nông dân huyền thoại — thu 2000 nông sản", "Legendary Farmer — harvest 2000 crops" },
        { "Nông dân lành nghề — thu 500 nông sản", "Skilled Farmer — harvest 500 crops" },
        { "Nông dân tập sự — thu 100 nông sản", "Apprentice Farmer — harvest 100 crops" },
        { "Nấu 10 món bo_ham_ca_rot", "Cook 10 Beef and Carrot Stew" },
        { "Nấu 10 món com_chien_trung", "Cook 10 Egg Fried Rice" },
        { "Nấu 10 món pho_beef", "Cook 10 Rare Beef Pho" },
        { "Nấu 10 món trung_chien_ca_chua", "Cook 10 Tomato Omelette" },
        { "Nấu 10 món ăn", "Cook 10 dishes" },
        { "Nấu 11 món bo_ham_ca_rot", "Cook 11 Beef and Carrot Stew" },
        { "Nấu 11 món com_chien_trung", "Cook 11 Egg Fried Rice" },
        { "Nấu 11 món ga_xao_ot", "Cook 11 Chili Chicken" },
        { "Nấu 11 món pho_beef", "Cook 11 Rare Beef Pho" },
        { "Nấu 11 món trung_chien_ca_chua", "Cook 11 Tomato Omelette" },
        { "Nấu 12 món bo_ham_ca_rot", "Cook 12 Beef and Carrot Stew" },
        { "Nấu 12 món com_chien_trung", "Cook 12 Egg Fried Rice" },
        { "Nấu 12 món ga_xao_ot", "Cook 12 Chili Chicken" },
        { "Nấu 12 món pho_beef", "Cook 12 Rare Beef Pho" },
        { "Nấu 12 món trung_chien_ca_chua", "Cook 12 Tomato Omelette" },
        { "Nấu 13 món bo_ham_ca_rot", "Cook 13 Beef and Carrot Stew" },
        { "Nấu 13 món com_chien_trung", "Cook 13 Egg Fried Rice" },
        { "Nấu 13 món ga_xao_ot", "Cook 13 Chili Chicken" },
        { "Nấu 13 món pho_beef", "Cook 13 Rare Beef Pho" },
        { "Nấu 13 món trung_chien_ca_chua", "Cook 13 Tomato Omelette" },
        { "Nấu 14 món bo_ham_ca_rot", "Cook 14 Beef and Carrot Stew" },
        { "Nấu 14 món com_chien_trung", "Cook 14 Egg Fried Rice" },
        { "Nấu 14 món ga_xao_ot", "Cook 14 Chili Chicken" },
        { "Nấu 14 món pho_beef", "Cook 14 Rare Beef Pho" },
        { "Nấu 14 món trung_chien_ca_chua", "Cook 14 Tomato Omelette" },
        { "Nấu 15 món bo_ham_ca_rot", "Cook 15 Beef and Carrot Stew" },
        { "Nấu 15 món com_chien_trung", "Cook 15 Egg Fried Rice" },
        { "Nấu 15 món ga_xao_ot", "Cook 15 Chili Chicken" },
        { "Nấu 15 món pho_beef", "Cook 15 Rare Beef Pho" },
        { "Nấu 15 món trung_chien_ca_chua", "Cook 15 Tomato Omelette" },
        { "Nấu 15 món ăn", "Cook 15 dishes" },
        { "Nấu 16 món bo_ham_ca_rot", "Cook 16 Beef and Carrot Stew" },
        { "Nấu 16 món ga_xao_ot", "Cook 16 Chili Chicken" },
        { "Nấu 16 món pho_beef", "Cook 16 Rare Beef Pho" },
        { "Nấu 2 món ga_xao_ot", "Cook 2 Chili Chicken" },
        { "Nấu 2 món trung_chien_ca_chua", "Cook 2 Tomato Omelette" },
        { "Nấu 2 món ăn", "Cook 2 dishes" },
        { "Nấu 25 món ăn", "Cook 25 dishes" },
        { "Nấu 3 món bò hầm cà rốt", "Cook 3 Beef and Carrot Stew" },
        { "Nấu 3 món pho_beef", "Cook 3 Rare Beef Pho" },
        { "Nấu 3 món trung_chien_ca_chua", "Cook 3 Tomato Omelette" },
        { "Nấu 3 món ăn", "Cook 3 dishes" },
        { "Nấu 4 món com_chien_trung", "Cook 4 Egg Fried Rice" },
        { "Nấu 4 món pho_beef", "Cook 4 Rare Beef Pho" },
        { "Nấu 40 món ăn", "Cook 40 dishes" },
        { "Nấu 5 món bo_ham_ca_rot", "Cook 5 Beef and Carrot Stew" },
        { "Nấu 5 món bò hầm cà rốt", "Cook 5 Beef and Carrot Stew" },
        { "Nấu 5 món com_chien_trung", "Cook 5 Egg Fried Rice" },
        { "Nấu 5 món pho_beef", "Cook 5 Rare Beef Pho" },
        { "Nấu 5 món ăn", "Cook 5 dishes" },
        { "Nấu 55 món ăn", "Cook 55 dishes" },
        { "Nấu 6 món bo_ham_ca_rot", "Cook 6 Beef and Carrot Stew" },
        { "Nấu 6 món com_chien_trung", "Cook 6 Egg Fried Rice" },
        { "Nấu 6 món ga_xao_ot", "Cook 6 Chili Chicken" },
        { "Nấu 7 món bo_ham_ca_rot", "Cook 7 Beef and Carrot Stew" },
        { "Nấu 7 món ga_xao_ot", "Cook 7 Chili Chicken" },
        { "Nấu 7 món trung_chien_ca_chua", "Cook 7 Tomato Omelette" },
        { "Nấu 70 món ăn", "Cook 70 dishes" },
        { "Nấu 8 món bo_ham_ca_rot", "Cook 8 Beef and Carrot Stew" },
        { "Nấu 8 món ga_xao_ot", "Cook 8 Chili Chicken" },
        { "Nấu 8 món pho_beef", "Cook 8 Rare Beef Pho" },
        { "Nấu 8 món trung_chien_ca_chua", "Cook 8 Tomato Omelette" },
        { "Nấu 9 món com_chien_trung", "Cook 9 Egg Fried Rice" },
        { "Nấu 9 món ga_xao_ot", "Cook 9 Chili Chicken" },
        { "Nấu 9 món pho_beef", "Cook 9 Rare Beef Pho" },
        { "Nấu 9 món trung_chien_ca_chua", "Cook 9 Tomato Omelette" },
        { "Nấu món bò hầm cà rốt", "Cook Beef and Carrot Stew" },
        { "Nấu món ăn đầu tiên", "Cook your first dish" },
        { "Thu 1 thịt heo", "Collect 1 Pork" },
        { "Thu 3 sữa bò", "Collect 3 Milk" },
        { "Thu 4 quả trứng", "Collect 4 Eggs" },
        { "Thu 6 quả trứng", "Collect 6 Eggs" },
        { "Thu 8 sản phẩm vật nuôi", "Collect 8 animal products" },
        { "Thu hoạch 10 rice", "Harvest 10 Rice" },
        { "Thu hoạch 100 hoa_hong", "Harvest 100 Roses" },
        { "Thu hoạch 100 nông sản", "Harvest 100 crops" },
        { "Thu hoạch 100 rice", "Harvest 100 Rice" },
        { "Thu hoạch 105 carot", "Harvest 105 Carrot" },
        { "Thu hoạch 105 sugarcane", "Harvest 105 Sugarcane" },
        { "Thu hoạch 110 hoa_hong", "Harvest 110 Roses" },
        { "Thu hoạch 110 rice", "Harvest 110 Rice" },
        { "Thu hoạch 115 carot", "Harvest 115 Carrot" },
        { "Thu hoạch 115 sugarcane", "Harvest 115 Sugarcane" },
        { "Thu hoạch 120 hoa_hong", "Harvest 120 Roses" },
        { "Thu hoạch 120 rice", "Harvest 120 Rice" },
        { "Thu hoạch 125 carot", "Harvest 125 Carrot" },
        { "Thu hoạch 125 sugarcane", "Harvest 125 Sugarcane" },
        { "Thu hoạch 130 hoa_hong", "Harvest 130 Roses" },
        { "Thu hoạch 130 rice", "Harvest 130 Rice" },
        { "Thu hoạch 135 carot", "Harvest 135 Carrot" },
        { "Thu hoạch 135 sugarcane", "Harvest 135 Sugarcane" },
        { "Thu hoạch 140 hoa_hong", "Harvest 140 Roses" },
        { "Thu hoạch 140 rice", "Harvest 140 Rice" },
        { "Thu hoạch 145 carot", "Harvest 145 Carrot" },
        { "Thu hoạch 145 sugarcane", "Harvest 145 Sugarcane" },
        { "Thu hoạch 15 carot", "Harvest 15 Carrot" },
        { "Thu hoạch 15 nông sản", "Harvest 15 crops" },
        { "Thu hoạch 150 hoa_hong", "Harvest 150 Roses" },
        { "Thu hoạch 150 rice", "Harvest 150 Rice" },
        { "Thu hoạch 20 ngô", "Harvest 20 Corn" },
        { "Thu hoạch 20 nông sản", "Harvest 20 crops" },
        { "Thu hoạch 20 rice", "Harvest 20 Rice" },
        { "Thu hoạch 200 nông sản", "Harvest 200 crops" },
        { "Thu hoạch 24 lúa", "Harvest 24 Rice" },
        { "Thu hoạch 25 carot", "Harvest 25 Carrot" },
        { "Thu hoạch 30 hoa_hong", "Harvest 30 Roses" },
        { "Thu hoạch 35 carot", "Harvest 35 Carrot" },
        { "Thu hoạch 35 sugarcane", "Harvest 35 Sugarcane" },
        { "Thu hoạch 350 nông sản", "Harvest 350 crops" },
        { "Thu hoạch 4 hoa hướng dương", "Harvest 4 Sunflowers" },
        { "Thu hoạch 4 hoa hồng", "Harvest 4 Roses" },
        { "Thu hoạch 40 hoa_hong", "Harvest 40 Roses" },
        { "Thu hoạch 40 nông sản", "Harvest 40 crops" },
        { "Thu hoạch 45 sugarcane", "Harvest 45 Sugarcane" },
        { "Thu hoạch 5 sugarcane", "Harvest 5 Sugarcane" },
        { "Thu hoạch 50 hoa_hong", "Harvest 50 Roses" },
        { "Thu hoạch 50 nông sản", "Harvest 50 crops" },
        { "Thu hoạch 50 rice", "Harvest 50 Rice" },
        { "Thu hoạch 55 carot", "Harvest 55 Carrot" },
        { "Thu hoạch 55 sugarcane", "Harvest 55 Sugarcane" },
        { "Thu hoạch 60 rice", "Harvest 60 Rice" },
        { "Thu hoạch 65 carot", "Harvest 65 Carrot" },
        { "Thu hoạch 65 sugarcane", "Harvest 65 Sugarcane" },
        { "Thu hoạch 70 hoa_hong", "Harvest 70 Roses" },
        { "Thu hoạch 70 rice", "Harvest 70 Rice" },
        { "Thu hoạch 75 carot", "Harvest 75 Carrot" },
        { "Thu hoạch 75 sugarcane", "Harvest 75 Sugarcane" },
        { "Thu hoạch 8 nông sản", "Harvest 8 crops" },
        { "Thu hoạch 80 hoa_hong", "Harvest 80 Roses" },
        { "Thu hoạch 80 rice", "Harvest 80 Rice" },
        { "Thu hoạch 85 carot", "Harvest 85 Carrot" },
        { "Thu hoạch 85 sugarcane", "Harvest 85 Sugarcane" },
        { "Thu hoạch 90 hoa_hong", "Harvest 90 Roses" },
        { "Thu hoạch 90 rice", "Harvest 90 Rice" },
        { "Thu hoạch 95 carot", "Harvest 95 Carrot" },
        { "Thu hoạch 95 sugarcane", "Harvest 95 Sugarcane" },
        { "Thu thập 10 Bắp Cải", "Collect 10 Cabbage" },
        { "Thu thập 10 Cà Chua", "Collect 10 Tomato" },
        { "Thu thập 10 Lúa", "Collect 10 Rice" },
        { "Thu thập 10 Ngô", "Collect 10 Corn" },
        { "Thu thập 3 Hoa Hồng", "Collect 3 Roses" },
        { "Thu thập 3 Hoa Lan", "Collect 3 Orchids" },
        { "Thu thập 3 Hướng Dương", "Collect 3 Sunflowers" },
        { "Thu thập 3 Thịt Bò", "Collect 3 Beef" },
        { "Thu thập 3 Thịt Gà", "Collect 3 Chicken" },
        { "Thu thập 3 Thịt Heo", "Collect 3 Pork" },
        { "Thu thập 3 Tulip", "Collect 3 Tulips" },
        { "Thu thập 5 Chanh", "Collect 5 Lemons" },
        { "Thu thập 5 Mía", "Collect 5 Sugarcane" },
        { "Thu thập 5 Nấm", "Collect 5 Mushrooms" },
        { "Thu thập 5 Tiêu", "Collect 5 Pepper" },
        { "Thu thập 5 Trứng", "Collect 5 Eggs" },
        { "Thu thập 5 Ớt", "Collect 5 Chili" },
        { "Thương lái — 300 đơn", "Trader — 300 orders" },
        { "Thợ chế biến — 50 sản phẩm", "Craftsperson — 50 products" },
        { "Trồng 10 cây bất kỳ", "Plant 10 crops of any kind" },
        { "Trồng 4 mía", "Plant 4 Sugarcane" },
        { "Trồng 6 ô hoa hướng dương", "Plant 6 Sunflower plots" },
        { "Trồng 8 ô lúa", "Plant 8 Rice plots" },
        { "Vươn xa — đạt L20", "Growing Big — reach L20" },
        { "Xay 4 bột gạo", "Mill 4 Rice Flour" },
        { "Ép 4 nước mía", "Press 4 Sugarcane Juice" },
        { "Đạt cấp 10", "Reach Level 10" },
        { "Đạt cấp 15", "Reach Level 15" },
        { "Đạt cấp 2", "Reach Level 2" },
        { "Đạt cấp 20", "Reach Level 20" },
        { "Đạt cấp 25", "Reach Level 25" },
        { "Đạt cấp 30 — Bậc thầy Nông trại", "Reach Level 30 — Farm Master" },
        { "Đạt cấp 6", "Reach Level 6" },
        { "Đầu bếp nhỏ — nấu 30 món", "Little Chef — cook 30 dishes" },

        // -- Chuoi trong code UI runtime --
        { "+\nÔ trống", "+\nEmpty slot" },
        { "Bán vật phẩm", "Sell an item" },
        { "Bạn có đủ hàng rồi! Chạm vào nhà có bong bóng để giao đơn nhé!", "You have everything you need! Tap the house with the bubble to deliver!" },
        { "BẬT LOA", "SPEAKER ON" },
        { "Bến không hợp lệ", "Invalid dock" },
        { "Bến đã mở khóa", "Dock already unlocked" },
        { "Bếp trưởng", "Head Chef" },
        { "Bỏ qua bước này", "Skip this step" },
        { "CHẠM ĐỂ CẤT VÀO KHO!", "TAP TO STORE IT!" },
        { "Chuồng bò sữa đã mở bán — bò sữa ăn lúa/ngô cho sữa giao đơn làng đó!", "The Dairy Pen is on sale — dairy cows eat rice or corn and give milk for village orders!" },
        { "Chuồng bò đã mở bán — cho bò ăn lúa/ngô để lấy thịt bò nhé!", "The Cow Pen is on sale — feed cows rice or corn to get beef!" },
        { "Chuồng gà đã mở bán! Vào Shop mua chuồng gà (100 vàng) rồi cho gà ăn nhé!", "The Chicken Coop is on sale! Buy it in the Shop (100 gold) and feed your chickens!" },
        { "Chuồng heo đã mở bán — heo ăn bắp cải/cà rốt cho thịt heo đó!", "The Pig Pen is on sale — pigs eat cabbage or carrots and give you pork!" },
        { "Chín", "Ripe" },
        { "Chúc mừng! Nông trại của bạn đã nổi tiếng khắp vùng rồi đó!", "Congratulations! Your farm is famous all over the region!" },
        { "Chưa chọn vật phẩm.", "No item selected." },
        { "Chưa chọn ô đất.", "No plot selected." },
        { "Chưa có gia vị — về nông trại mở KHO,\nchọn gia vị rồi bấm GỬI BẾP nhé!", "No seasonings yet — go back to the farm, open STORAGE,\npick seasonings and tap SEND TO KITCHEN!" },
        { "Chưa có khách chờ", "No guests waiting" },
        { "Chưa gán crop mặc định.", "No default crop assigned." },
        { "Chưa mở được, thử lại nhé!", "Could not open it, please try again!" },
        { "Chưa nhận được thưởng — món vẫn còn nguyên trong kho.", "No reward yet — the dish is still safe in storage." },
        { "Chưa sẵn sàng, thử lại sau giây lát.", "Not ready yet, try again in a moment." },
        { "Chưa sẵn sàng, thử lại sau.", "Not ready yet, please try again." },
        { "Chưa đủ điểm! Hãy thử lại nhé!", "Not enough points! Give it another try!" },
        { "Chưa ổn lắm! Thử lại nào!", "Not quite! Try again!" },
        { "Chạm bàn trình bày để cất vào kho →", "Tap the plating table to store it →" },
        { "Chạm từng toa để thu — thu hết các toa, tàu sẽ rời ga!", "Tap each wagon to collect — collect them all and the train leaves!" },
        { "Chạm vào chuồng để cho gà ăn (1 lúa hoặc ngô)!", "Tap the coop to feed your chickens (1 rice or corn)!" },
        { "Chạm để tiếp tục", "Tap to continue" },
        { "Chọn lại nguyên liệu rồi nấu tiếp nhé!", "Pick your ingredients again and cook once more!" },
        { "Crop rỗng.", "Crop is empty." },
        { "CẦN NHỮNG THỨ NÀY", "YOU WILL NEED" },
        { "Gia vị 0/3", "Seasonings 0/3" },
        { "Gieo nốt hạt lúa cho kín cả 8 ô ruộng nhé — bàn tay sẽ chỉ ô còn trống cho bạn!", "Sow rice in all 8 plots — the hand will point out the empty ones!" },
        { "Gỗ tấm", "Wood Plank" },
        { "Hãy chọn một vật phẩm.", "Please pick an item." },
        { "Hương vị", "Flavour" },
        { "Hạt Hoa Hướng Dương", "Sunflower Seeds" },
        { "Hạt giống rỗng.", "Seed is empty." },
        { "Hết hạn", "Expired" },
        { "Hệ thống bến tàu chưa sẵn sàng", "The dock system is not ready yet" },
        { "KHÔNG CÒN VẬT PHẨM NÀO ĐỂ BÁN", "NOTHING LEFT TO SELL" },
        { "Khay trống — về nông trại mở KHO,\nchọn nguyên liệu rồi bấm GỬI BẾP nhé!", "Tray is empty — go back to the farm, open STORAGE,\npick ingredients and tap SEND TO KITCHEN!" },
        { "Kho đầy — bán bớt hoặc nâng cấp kho rồi nhận món.", "Storage is full — sell something or upgrade it, then collect the dish." },
        { "Khá tốt! Cố gắng thêm nhé!", "Pretty good! Keep it up!" },
        { "Khách này không nhận món lúc này.", "This guest is not taking a dish right now." },
        { "Khách đang xem thực đơn — đợi một chút nhé!", "The guest is reading the menu — one moment!" },
        { "Không lấy được hàng từ kho.", "Could not take the item from storage." },
        { "Không tìm thấy hạt giống.", "Seed not found." },
        { "Không tìm thấy ô đất.", "Plot not found." },
        { "Không đủ gem", "Not enough gems" },
        { "Kéo lưỡi liềm qua cây để thu hoạch.", "Swipe the sickle over the crop to harvest it." },
        { "Kết cấu", "Texture" },
        { "LÒ ĐANG CHÁY...", "THE STOVE IS HOT..." },
        { "Lò đã nghỉ", "Stove is resting" },
        { "Lúa chín vàng cả ruộng rồi! Quẹt liềm thu hoạch nốt những ô còn lại nào.", "The whole field is golden! Swipe the sickle to harvest the rest." },
        { "MÓN HÔM NAY", "TODAY'S SPECIAL" },
        { "MÓN TRÊN DĨA", "DISH ON THE PLATE" },
        { "Mèo Thần Tài", "Lucky Cat" },
        { "Món ăn hôm nay", "Today's Dish" },
        { "Mặt hàng này không còn được bán.", "This item is no longer for sale." },
        { "Mẹo: bí đỏ và dưa hấu trồng lâu hơn nhưng bán đắt hơn hẳn.", "Tip: pumpkin and watermelon take longer to grow but sell for a lot more." },
        { "Mẹo: cây chín sẽ đung đưa nhè nhẹ, nhìn ruộng là biết cây nào thu được.", "Tip: ripe crops sway gently, so one look tells you what is ready." },
        { "Mẹo: gia vị mua ở chợ — muối, tiêu, chanh, ớt — đều mang vào bếp được.", "Tip: seasonings from the market — salt, pepper, lemon, chili — can all go to the kitchen." },
        { "Mẹo: giá ở chợ đắt hơn tự nấu — tiền công nấu nằm trong đó.", "Tip: market prices beat cooking it yourself — the cook is paid too." },
        { "Mẹo: món nấu đúng CẢ nguyên liệu lẫn hương vị mới đạt 100 điểm.", "Tip: match BOTH the ingredients and the flavours to score 100." },
        { "Mẹo: mở sổ công thức trong bếp để xem món nào sắp mở khoá.", "Tip: open the recipe book in the kitchen to see which dish unlocks next." },
        { "Mẹo: nguyên liệu nấu được món mới chuyển sang bếp được — hạt giống thì không.", "Tip: only cookable ingredients can go to the kitchen — seeds cannot." },
        { "Mẹo: đơn hàng dân làng trả thêm vàng so với bán thẳng ở chợ.", "Tip: village orders pay more gold than selling straight at the market." },
        { "Mở shop hạt giống.", "Opening the seed shop." },
        { "NHÀ BẾP đã mở! Vào nấu món đầu tiên nào!", "The KITCHEN is open! Go cook your very first dish!" },
        { "NHẬN THƯỞNG", "CLAIM REWARDS" },
        { "Nghe nói du khách phương xa rất muốn ghé thăm... Bến tàu cũ ngoài bãi biển có thể sửa lại được đấy!", "They say travellers from far away want to visit... the old dock on the beach could be repaired!" },
        { "Nguyên liệu 0/4", "Ingredients 0/4" },
        { "Người chơi", "You" },
        { "Ngọt", "Sweet" },
        { "Nhìn kìa — chuyến tàu đầu tiên đang tới!", "Look — the very first boat is coming in!" },
        { "Nhìn ra biển nào!", "Look out to sea!" },
        { "Nạp đủ hàng cho các toa để tàu khởi hành vận chuyển!", "Fill every wagon and the train will set off!" },
        { "NẤU!", "COOK!" },
        { "QUẦY HÀNG", "MARKET STALL" },
        { "Rất tốt! Gần hoàn hảo!", "Very good! Nearly perfect!" },
        { "Số lượng phải lớn hơn 0.", "Quantity must be more than 0." },
        { "Thiếu FarmEconomyManager — chưa trừ tiền được!", "FarmEconomyManager is missing — cannot take payment!" },
        { "Thu hoạch thất bại.", "Harvest failed." },
        { "Thêm ô", "Add slot" },
        { "Trừ vàng thất bại.", "Could not deduct the gold." },
        { "Tuyệt vời! Gần như hoàn hảo!", "Wonderful! Almost perfect!" },
        { "TÀU LỬA", "TRAIN" },
        { "Tàu chở hàng đã đến! Chất nông sản lên tàu để nhận thưởng lớn!", "The freight train has arrived! Load your crops for a big reward!" },
        { "Tàu du lịch sẽ cập bến thường xuyên — du khách sẽ dạo chơi, ngắm nông trại và thưởng thức đặc sản của bạn!", "Tour boats will dock often — guests will stroll around, admire your farm and taste your specialities!" },
        { "Tàu đang rời ga... chuyến tàu mới sắp tới!", "The train is leaving... a new one is on the way!" },
        { "Tàu đang vào ga — chờ một chút nhé!", "The train is pulling in — just a moment!" },
        { "Tàu đã về — có hàng cho bạn!", "The train is back — goods for you!" },
        { "Tất cả các toa đã đủ hàng! Tàu đang khởi hành...", "Every wagon is loaded! The train is departing..." },
        { "TẮT LOA", "SPEAKER OFF" },
        { "VỊ KHÁCH MUỐN", "FLAVOURS WANTED" },
        { "cất vào kho trước đã", "store it first" },
        { "Ô này chưa tới lượt mở.", "This slot is not ready to open yet." },
        { "Ô này không dùng được.", "This slot cannot be used." },
        { "ĐANG NẤU...", "COOKING..." },
        { "ĐANG VẬN CHUYỂN", "ON THE WAY" },
        { "Đang chọn món...", "Choosing a dish..." },
        { "Đang tải", "Loading" },
        { "Đang vận chuyển...", "On the way..." },
        { "Điểm dự kiến:  — đ", "Score preview:  — pt" },
        { "Đá xây dựng", "Building Stone" },
        { "Đã gỡ hàng, hoàn về kho.", "Item taken down and returned to storage." },
        { "Đã mở thêm một ô quầy!", "A new stall slot is open!" },
        { "Đã nạp đủ tất cả toa! Tàu đang chuẩn bị khởi hành vận chuyển.", "Every wagon is loaded! The train is getting ready to leave." },
        { "Đã đặt lên quầy!", "Put on the stall!" },
        { "Đường", "Sugar" },
        { "Đậm", "Savoury" },
        { "Đậm đà", "Savoury" },
        { "Đặt lên quầy", "Put on the stall" },
        { "‹ Xem món khác", "‹ See other dishes" },

        // -- Mau chuoi co tham so (Loc.TF) — {0},{1}... phai giu nguyen ------
        // Sua mau o day thi PHAI sua ca chuoi tieng Viet trong code cho khop.
        { " ({0}/{1} ô)", " ({0}/{1} slots)" },
        { "+ Mở {0} ô\n{1:N0} vàng", "+ Unlock {0} slots\n{1:N0} gold" },
        { "+{0} vàng   +{1} EXP   Bán {2}", "+{0} gold   +{1} EXP   Sells {2}" },
        { "Cao hơn giá gợi ý ({0:N0}) — lâu bán hơn", "Above the suggested price ({0:N0}) — sells slower" },
        { "Chưa có nhiệm vụ", "No quests yet" },
        { "Chưa có {0} trong kho — vào bếp nấu nhé!", "No {0} in storage — go and cook one!" },
        { "Chưa có {0} trong kho. Hãy chế biến tại Máy Xay Thức Ăn hoặc thu hoạch nông sản!", "No {0} in storage. Make some at the Feed Mill, or harvest crops!" },
        { "Chưa đủ cấp\nCấp {0}", "Level too low\nLv {0}" },
        { "Chọn {0}/{1}", "Picked {0}/{1}" },
        { "Còn thiếu {0} ({1}/{2}).", "Still need {0} ({1}/{2})." },
        { "Cấp Tối Đa ({0}) · Sức chứa: {1} Slot", "Max Level ({0}) · Capacity: {1} slots" },
        { "Cấp {0}", "Lv {0}" },
        { "Cấp {0}\n{1}", "Lv {0}\n{1}" },
        { "Cấp {0} · Sức chứa: {1} Slot (Nâng cấp: +25 Slot)", "Level {0} · Capacity: {1} slots (Upgrade: +25 slots)" },
        { "Cần cấp {0} mới vào được Bếp.", "Reach Level {0} to enter the Kitchen." },
        { "Cần {0} kim cương để tăng tốc.", "Need {0} gems to speed this up." },
        { "Cần đạt cấp {0}", "Reach Level {0} first" },
        { "Gia vị  {0}/3", "Seasonings  {0}/3" },
        { "Giá gợi ý · {0:N0}/cái", "Suggested price · {0:N0} each" },
        { "HỎNG... {0}đ", "RUINED... {0} pts" },
        { "Kho đầy ({0}/{1} slot) — bán bớt hoặc nâng cấp kho rồi thu hoạch.", "Storage full ({0}/{1} slots) — sell some or upgrade, then harvest." },
        { "Kho đầy{0} — chưa nhận được \"{1}\". Bán bớt hoặc nâng cấp kho.", "Storage full{0} — \"{1}\" was not collected. Sell some or upgrade your storage." },
        { "Không thể trồng {0} ở ô {1}", "Cannot plant {0} in plot {1}" },
        { "Không đủ vàng (cần {0}).", "Not enough gold (need {0})." },
        { "Không đủ vàng để bật loa (cần {0}).", "Not enough gold for the speaker (need {0})." },
        { "Không đủ {0:N0} vàng để mở ô!", "Not enough gold ({0:N0}) to unlock a slot!" },
        { "Không đủ {0}!", "Not enough {0}!" },
        { "Không đủ {0}! Cần {1}, đang có {2}.", "Not enough {0}! Need {1}, you have {2}." },
        { "Kéo hạt giống hoa để trồng vào ô {0}", "Drag a flower seed to plant in plot {0}" },
        { "Kéo hạt giống để trồng vào ô {0}", "Drag a seed to plant in plot {0}" },
        { "Lên cấp {0}! Quà mới đã vào kho của bạn.", "Level {0}! New gifts are waiting in your storage." },
        { "Món hôm nay! +{0} vàng thưởng thêm.", "Today's special! +{0} bonus gold." },
        { "Mở bến số {0}", "Unlock Dock {0}" },
        { "Mở ở Lv{0}", "Unlocks at Lv{0}" },
        { "Mở ở Lv{0}\n{1} Kim Cương", "Unlocks at Lv{0}\n{1} Gems" },
        { "Mở ở Lv{0}\n{1} vàng", "Unlocks at Lv{0}\n{1} gold" },
        { "Mở ở cấp {0}", "Unlocks at Lv {0}" },
        { "Nguyên liệu  {0}/4", "Ingredients  {0}/4" },
        { "Nguyên liệu nông sản tươi ngon. Dùng để nấu ăn tại bếp hoặc bán tại quầy. Giá tham khảo {0} vàng/cái.", "Fresh farm produce. Cook with it in the kitchen or sell it at your stall. About {0} gold each." },
        { "Nhiệm Vụ Mới", "New Quest" },
        { "Slot #{0} chưa mở", "Slot #{0} is locked" },
        { "Slot #{0} đang có hàng", "Slot #{0} is busy" },
        { "Sơ chế: {0}", "Prepping: {0}" },
        { "Sẽ cập bến sau {0} phút. Hãy chuẩn bị món ăn đón khách nhé!", "Docking in {0} minutes. Get your dishes ready for the guests!" },
        { "Thấp hơn giá gợi ý ({0:N0}) — bán nhanh hơn", "Below the suggested price ({0:N0}) — sells faster" },
        { "Trong kho chỉ còn {0}.", "Only {0} left in storage." },
        { "XONG! {0}đ", "DONE! {0} pts" },
        { "Yêu cầu: đạt Lv{0} (bạn đang Lv{1})", "Requires Lv{0} (you're Lv{1})" },
        { "{0} giây", "{0}s" },
        { "{0} nguyên liệu · {1} gia vị", "{0} ingredients · {1} seasonings" },
        { "{0} · Cấp {1}", "{0} · Lv {1}" },
        { "{0} · Cấp {1} · {2} vàng", "{0} · Lv {1} · {2} gold" },
        { "{0} Điểm", "{0} pts" },
        { "{0}/{1} slot đã mở · {2} đang xay · {3} chờ thu", "{0}/{1} slots open · {2} milling · {3} ready" },
        { "Ô đất {0} chưa mở khóa.", "Plot {0} is still locked." },
        { "Đang xay · {0} slot", "Milling · {0} slots" },
        { "Điểm dự kiến:  {0}đ", "Score preview:  {0} pts" },
        { "Đã cho {0} vào slot {1}", "Added {0} to slot {1}" },
        { "Đã gửi {0} món", "{0} dishes sent" },
        { "Đã mua {0}{1}!", "Bought {0}{1}!" },
        { "Đã mở thêm {0} ô khay!", "{0} more tray slots unlocked!" },
        { "Đã thu hoạch {0} ở ô {1}", "Harvested {0} from plot {1}" },
        { "Đã thu {0} vào kho!", "Collected {0} into storage!" },
        { "Đã trồng {0} ô {1}", "Planted {0} plots of {1}" },
        { "Đã trồng {0} ở ô {1}", "Planted {0} in plot {1}" },
        { "Đã xay xong {0}", "{0} is ready" },
        { "Đến", "Go" },
        { "Ủ {0}", "Brew {0}" },
        { "⚓ Tàu số {0:00} sắp cập bến!", "⚓ Boat {0:00} is arriving soon!" },
        { "🔒 Mở ở cấp {0}", "🔒 Unlocks at Lv {0}" },

    };
}
